// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    diaryFts,
    diaries,
    diaryLinks,
    diaryChunks,
    idxDiaryChunksDiary,
    embedQueue,
    llmProviders,
    idxLlmProvidersSort,
    chatSessions,
    idxChatSessionsUpdated,
    chatMessages,
    idxChatMessagesSession,
    assistantToolCalls,
    memories,
    idxMemoriesUpdated,
    agentPresets,
    tombstones,
    idxTombstonesTime,
    categories,
    fonts,
    mediaInfos,
    places,
    idxDiariesShowTime,
    idxDiariesShowCatTime,
    idxDiariesShowLastmod,
    diaryMedia,
    idxDiaryMediaKind,
    idxDiaryMediaFile,
    diaryTags,
    idxDiaryTagsTag,
    idxDiaryLinksDst,
  ];
  late final Shape0 diaryFts = Shape0(
    source: i0.VersionedVirtualTable(
      entityName: 'diary_fts',
      moduleAndArgs: 'fts5(title_tok, body_tok, content=\'\', contentless_delete=1, tokenize=\'unicode61\', prefix=\'2\', detail=full, columnsize=1)',
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 diaries = Shape1(
    source: i0.VersionedTable(
      entityName: 'diaries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 diaryLinks = Shape2(
    source: i0.VersionedTable(
      entityName: 'diary_links',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(src_id, dst_id)'],
      columns: [_column_18, _column_19],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 diaryChunks = Shape3(
    source: i0.VersionedTable(
      entityName: 'diary_chunks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(diary_id, seq)'],
      columns: [
        _column_2,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxDiaryChunksDiary = i1.Index(
    'idx_diary_chunks_diary',
    'CREATE INDEX idx_diary_chunks_diary ON diary_chunks (diary_id)',
  );
  late final Shape4 embedQueue = Shape4(
    source: i0.VersionedTable(
      entityName: 'embed_queue',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 llmProviders = Shape5(
    source: i0.VersionedTable(
      entityName: 'llm_providers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_27,
        _column_28,
        _column_12,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxLlmProvidersSort = i1.Index(
    'idx_llm_providers_sort',
    'CREATE INDEX idx_llm_providers_sort ON llm_providers (sort_order)',
  );
  late final Shape6 chatSessions = Shape6(
    source: i0.VersionedTable(
      entityName: 'chat_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_27,
        _column_38,
        _column_39,
        _column_40,
        _column_31,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxChatSessionsUpdated = i1.Index(
    'idx_chat_sessions_updated',
    'CREATE INDEX idx_chat_sessions_updated ON chat_sessions (updated_at DESC)',
  );
  late final Shape7 chatMessages = Shape7(
    source: i0.VersionedTable(
      entityName: 'chat_messages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_27,
        _column_50,
        _column_51,
        _column_6,
        _column_31,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxChatMessagesSession = i1.Index(
    'idx_chat_messages_session',
    'CREATE INDEX idx_chat_messages_session ON chat_messages (session_id, created_at)',
  );
  late final Shape8 assistantToolCalls = Shape8(
    source: i0.VersionedTable(
      entityName: 'assistant_tool_calls',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(message_id, seq)'],
      columns: [
        _column_58,
        _column_21,
        _column_59,
        _column_28,
        _column_60,
        _column_61,
        _column_62,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 memories = Shape9(
    source: i0.VersionedTable(
      entityName: 'memories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_27, _column_63, _column_6, _column_31, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxMemoriesUpdated = i1.Index(
    'idx_memories_updated',
    'CREATE INDEX idx_memories_updated ON memories (updated_at DESC)',
  );
  late final Shape10 agentPresets = Shape10(
    source: i0.VersionedTable(
      entityName: 'agent_presets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_27,
        _column_28,
        _column_64,
        _column_65,
        _column_66,
        _column_31,
        _column_41,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 tombstones = Shape11(
    source: i0.VersionedTable(
      entityName: 'tombstones',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_67, _column_68, _column_69],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxTombstonesTime = i1.Index(
    'idx_tombstones_time',
    'CREATE INDEX idx_tombstones_time ON tombstones (time_ms)',
  );
  late final Shape12 categories = Shape12(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_27, _column_28, _column_9, _column_70, _column_71],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 fonts = Shape13(
    source: i0.VersionedTable(
      entityName: 'fonts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_72, _column_73, _column_74],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 mediaInfos = Shape14(
    source: i0.VersionedTable(
      entityName: 'media_infos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_75, _column_76, _column_77, _column_9],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 places = Shape15(
    source: i0.VersionedTable(
      entityName: 'places',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_27,
        _column_28,
        _column_78,
        _column_79,
        _column_80,
        _column_9,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxDiariesShowTime = i1.Index(
    'idx_diaries_show_time',
    'CREATE INDEX idx_diaries_show_time ON diaries (show, time DESC, id DESC)',
  );
  final i1.Index idxDiariesShowCatTime = i1.Index(
    'idx_diaries_show_cat_time',
    'CREATE INDEX idx_diaries_show_cat_time ON diaries (show, category_id, time DESC, id DESC)',
  );
  final i1.Index idxDiariesShowLastmod = i1.Index(
    'idx_diaries_show_lastmod',
    'CREATE INDEX idx_diaries_show_lastmod ON diaries (show, last_modified DESC, id DESC)',
  );
  late final Shape16 diaryMedia = Shape16(
    source: i0.VersionedTable(
      entityName: 'diary_media',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(diary_id, kind, seq)'],
      columns: [_column_81, _column_82, _column_21, _column_83],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxDiaryMediaKind = i1.Index(
    'idx_diary_media_kind',
    'CREATE INDEX idx_diary_media_kind ON diary_media (kind, diary_id)',
  );
  final i1.Index idxDiaryMediaFile = i1.Index(
    'idx_diary_media_file',
    'CREATE INDEX idx_diary_media_file ON diary_media (file_name)',
  );
  late final Shape17 diaryTags = Shape17(
    source: i0.VersionedTable(
      entityName: 'diary_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(diary_id, seq)'],
      columns: [_column_81, _column_21, _column_84],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxDiaryTagsTag = i1.Index(
    'idx_diary_tags_tag',
    'CREATE INDEX idx_diary_tags_tag ON diary_tags (tag)',
  );
  final i1.Index idxDiaryLinksDst = i1.Index(
    'idx_diary_links_dst',
    'CREATE INDEX idx_diary_links_dst ON diary_links (dst_id)',
  );
}

class Shape0 extends i0.VersionedVirtualTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get titleTok =>
      columnsByName['title_tok']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bodyTok =>
      columnsByName['body_tok']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title_tok',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body_tok',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get rid =>
      columnsByName['rid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categoryId =>
      columnsByName['category_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get content =>
      columnsByName['content']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentText =>
      columnsByName['content_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get time =>
      columnsByName['time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastModified =>
      columnsByName['last_modified']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get show =>
      columnsByName['show']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get mood =>
      columnsByName['mood']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get aspect =>
      columnsByName['aspect']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get placeId =>
      columnsByName['place_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get weatherIcon =>
      columnsByName['weather_icon']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get weatherTemp =>
      columnsByName['weather_temp']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get weatherText =>
      columnsByName['weather_text']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rid',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content_text',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'time',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_modified',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'show',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mood',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_13(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'aspect',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'place_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'weather_icon',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'weather_temp',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'weather_text',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get srcId =>
      columnsByName['src_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dstId =>
      columnsByName['dst_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'src_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES diaries(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dst_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get rid =>
      columnsByName['rid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get diaryId =>
      columnsByName['diary_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get seq =>
      columnsByName['seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get startOff =>
      columnsByName['start_off']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get len =>
      columnsByName['len']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get textHash =>
      columnsByName['text_hash']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'diary_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'seq',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_off',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'len',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'text_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get diaryId =>
      columnsByName['diary_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get enqueuedAt =>
      columnsByName['enqueued_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'diary_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enqueued_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get baseUrl =>
      columnsByName['base_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get defaultModel =>
      columnsByName['default_model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get presetId =>
      columnsByName['preset_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get modelsJson =>
      columnsByName['models_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get toolCall =>
      columnsByName['tool_call']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reasoning =>
      columnsByName['reasoning']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get attachment =>
      columnsByName['attachment']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'base_url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'default_model',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'preset_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'models_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'tool_call',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reasoning',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attachment',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get providerId =>
      columnsByName['provider_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get model =>
      columnsByName['model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get reasoningEffort =>
      columnsByName['reasoning_effort']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get compactedSummary =>
      columnsByName['compacted_summary']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get compactedUpToMessageId =>
      columnsByName['compacted_up_to_message_id']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get compactedAt =>
      columnsByName['compacted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get compactedInputTokensAtTrigger =>
      columnsByName['compacted_input_tokens_at_trigger']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get agentPresetId =>
      columnsByName['agent_preset_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get personaSnapshot =>
      columnsByName['persona_snapshot']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get toolsSnapshotJson =>
      columnsByName['tools_snapshot_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'provider_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'model',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reasoning_effort',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'compacted_summary',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'compacted_up_to_message_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'compacted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'compacted_input_tokens_at_trigger',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'agent_preset_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'persona_snapshot',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tools_snapshot_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get content =>
      columnsByName['content']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get reasoning =>
      columnsByName['reasoning']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get thinkingMillis =>
      columnsByName['thinking_millis']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get imageName =>
      columnsByName['image_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get inputTokens =>
      columnsByName['input_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get outputTokens =>
      columnsByName['output_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get model =>
      columnsByName['model']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES chat_sessions(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'role',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reasoning',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'thinking_millis',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'image_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'input_tokens',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'output_tokens',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'model',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get messageId =>
      columnsByName['message_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get seq =>
      columnsByName['seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get callId =>
      columnsByName['call_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get argsJson =>
      columnsByName['args_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get result =>
      columnsByName['result']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get done =>
      columnsByName['done']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'message_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES chat_messages(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'call_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'args_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'result',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<int> _column_62(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'done',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get content =>
      columnsByName['content']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get persona =>
      columnsByName['persona']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get toolsJson =>
      columnsByName['tools_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'persona',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tools_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get timeMs =>
      columnsByName['time_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get pushedBackendsJson =>
      columnsByName['pushed_backends_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_67(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<int> _column_68(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'time_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pushed_backends_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastModified =>
      columnsByName['last_modified']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get parentId =>
      columnsByName['parent_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get color =>
      columnsByName['color']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'parent_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_71(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'color',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get fontFamily =>
      columnsByName['font_family']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fontFileName =>
      columnsByName['font_file_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get wghtAxisJson =>
      columnsByName['wght_axis_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_72(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'font_family',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_73(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'font_file_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_74(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'wght_axis_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get fileName =>
      columnsByName['file_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastModified =>
      columnsByName['last_modified']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_75(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_76(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_77(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get latitude =>
      columnsByName['latitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get longitude =>
      columnsByName['longitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get icon =>
      columnsByName['icon']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastModified =>
      columnsByName['last_modified']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_78(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'latitude',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_79(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'longitude',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get diaryId =>
      columnsByName['diary_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get seq =>
      columnsByName['seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get fileName =>
      columnsByName['file_name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'diary_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES diaries(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_82(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_83(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape17 extends i0.VersionedTable {
  Shape17({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get diaryId =>
      columnsByName['diary_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get seq =>
      columnsByName['seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get tag =>
      columnsByName['tag']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_84(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tag',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    diaries,
    diaryLinks,
    diaryChunks,
    idxDiaryChunksDiary,
    embedQueue,
    llmProviders,
    idxLlmProvidersSort,
    chatSessions,
    idxChatSessionsUpdated,
    chatMessages,
    idxChatMessagesSession,
    assistantToolCalls,
    memories,
    idxMemoriesUpdated,
    tombstones,
    idxTombstonesTime,
    categories,
    fonts,
    mediaInfos,
    places,
    idxDiariesShowTime,
    idxDiariesShowCatTime,
    idxDiariesShowLastmod,
    diaryMedia,
    idxDiaryMediaKind,
    idxDiaryMediaFile,
    diaryTags,
    idxDiaryTagsTag,
    idxDiaryLinksDst,
    diaryFts,
  ];
  late final Shape1 diaries = Shape1(
    source: i0.VersionedTable(
      entityName: 'diaries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 diaryLinks = Shape2(
    source: i0.VersionedTable(
      entityName: 'diary_links',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(src_id, dst_id)'],
      columns: [_column_18, _column_19],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 diaryChunks = Shape3(
    source: i0.VersionedTable(
      entityName: 'diary_chunks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(diary_id, seq)'],
      columns: [
        _column_2,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxDiaryChunksDiary = i1.Index(
    'idx_diary_chunks_diary',
    'CREATE INDEX idx_diary_chunks_diary ON diary_chunks (diary_id)',
  );
  late final Shape4 embedQueue = Shape4(
    source: i0.VersionedTable(
      entityName: 'embed_queue',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 llmProviders = Shape5(
    source: i0.VersionedTable(
      entityName: 'llm_providers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_27,
        _column_28,
        _column_12,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxLlmProvidersSort = i1.Index(
    'idx_llm_providers_sort',
    'CREATE INDEX idx_llm_providers_sort ON llm_providers (sort_order)',
  );
  late final Shape18 chatSessions = Shape18(
    source: i0.VersionedTable(
      entityName: 'chat_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_27,
        _column_38,
        _column_39,
        _column_40,
        _column_31,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxChatSessionsUpdated = i1.Index(
    'idx_chat_sessions_updated',
    'CREATE INDEX idx_chat_sessions_updated ON chat_sessions (updated_at DESC)',
  );
  late final Shape19 chatMessages = Shape19(
    source: i0.VersionedTable(
      entityName: 'chat_messages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_27,
        _column_50,
        _column_51,
        _column_6,
        _column_31,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_85,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxChatMessagesSession = i1.Index(
    'idx_chat_messages_session',
    'CREATE INDEX idx_chat_messages_session ON chat_messages (session_id, created_at)',
  );
  late final Shape8 assistantToolCalls = Shape8(
    source: i0.VersionedTable(
      entityName: 'assistant_tool_calls',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(message_id, seq)'],
      columns: [
        _column_58,
        _column_21,
        _column_59,
        _column_28,
        _column_60,
        _column_61,
        _column_62,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 memories = Shape20(
    source: i0.VersionedTable(
      entityName: 'memories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_27,
        _column_63,
        _column_6,
        _column_31,
        _column_41,
        _column_86,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxMemoriesUpdated = i1.Index(
    'idx_memories_updated',
    'CREATE INDEX idx_memories_updated ON memories (updated_at DESC)',
  );
  late final Shape11 tombstones = Shape11(
    source: i0.VersionedTable(
      entityName: 'tombstones',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_67, _column_68, _column_69],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxTombstonesTime = i1.Index(
    'idx_tombstones_time',
    'CREATE INDEX idx_tombstones_time ON tombstones (time_ms)',
  );
  late final Shape12 categories = Shape12(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_27, _column_28, _column_9, _column_70, _column_71],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 fonts = Shape13(
    source: i0.VersionedTable(
      entityName: 'fonts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_72, _column_73, _column_74],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 mediaInfos = Shape14(
    source: i0.VersionedTable(
      entityName: 'media_infos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_75, _column_76, _column_77, _column_9],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 places = Shape15(
    source: i0.VersionedTable(
      entityName: 'places',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_27,
        _column_28,
        _column_78,
        _column_79,
        _column_80,
        _column_9,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxDiariesShowTime = i1.Index(
    'idx_diaries_show_time',
    'CREATE INDEX idx_diaries_show_time ON diaries (show, time DESC, id DESC)',
  );
  final i1.Index idxDiariesShowCatTime = i1.Index(
    'idx_diaries_show_cat_time',
    'CREATE INDEX idx_diaries_show_cat_time ON diaries (show, category_id, time DESC, id DESC)',
  );
  final i1.Index idxDiariesShowLastmod = i1.Index(
    'idx_diaries_show_lastmod',
    'CREATE INDEX idx_diaries_show_lastmod ON diaries (show, last_modified DESC, id DESC)',
  );
  late final Shape16 diaryMedia = Shape16(
    source: i0.VersionedTable(
      entityName: 'diary_media',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(diary_id, kind, seq)'],
      columns: [_column_81, _column_82, _column_21, _column_83],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxDiaryMediaKind = i1.Index(
    'idx_diary_media_kind',
    'CREATE INDEX idx_diary_media_kind ON diary_media (kind, diary_id)',
  );
  final i1.Index idxDiaryMediaFile = i1.Index(
    'idx_diary_media_file',
    'CREATE INDEX idx_diary_media_file ON diary_media (file_name)',
  );
  late final Shape17 diaryTags = Shape17(
    source: i0.VersionedTable(
      entityName: 'diary_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(diary_id, seq)'],
      columns: [_column_81, _column_21, _column_84],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxDiaryTagsTag = i1.Index(
    'idx_diary_tags_tag',
    'CREATE INDEX idx_diary_tags_tag ON diary_tags (tag)',
  );
  final i1.Index idxDiaryLinksDst = i1.Index(
    'idx_diary_links_dst',
    'CREATE INDEX idx_diary_links_dst ON diary_links (dst_id)',
  );
  late final Shape21 diaryFts = Shape21(
    source: i0.VersionedVirtualTable(
      entityName: 'diary_fts',
      moduleAndArgs: 'fts5(title, content_text, content=\'diaries\', content_rowid=\'rid\', tokenize=\'simple\')',
      columns: [_column_87, _column_88],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape18 extends i0.VersionedTable {
  Shape18({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get providerId =>
      columnsByName['provider_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get model =>
      columnsByName['model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get reasoningEffort =>
      columnsByName['reasoning_effort']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get compactedSummary =>
      columnsByName['compacted_summary']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get compactedUpToMessageId =>
      columnsByName['compacted_up_to_message_id']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get compactedAt =>
      columnsByName['compacted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get compactedInputTokensAtTrigger =>
      columnsByName['compacted_input_tokens_at_trigger']!
          as i1.GeneratedColumn<int>;
}

class Shape19 extends i0.VersionedTable {
  Shape19({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get content =>
      columnsByName['content']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get reasoning =>
      columnsByName['reasoning']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get thinkingMillis =>
      columnsByName['thinking_millis']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get imageName =>
      columnsByName['image_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get inputTokens =>
      columnsByName['input_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get outputTokens =>
      columnsByName['output_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get model =>
      columnsByName['model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get providerId =>
      columnsByName['provider_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_85(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'provider_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape20 extends i0.VersionedTable {
  Shape20({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get content =>
      columnsByName['content']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_86(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape21 extends i0.VersionedVirtualTable {
  Shape21({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentText =>
      columnsByName['content_text']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_87(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_88(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content_text',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
