// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_tools`, `drive`, `split_history`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProxyTool`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `call`, `definition`, `name`

/// 流式对话 + 多轮工具调用。Dart 取消订阅会令 `sink.add` 失败，循环随即中断（取消在途
/// 请求）。硬性失败（构造客户端 / 流错误）以 `Err` 形式让 Dart 流报错。
Stream<RigStreamEvent> rigChatStream({
  required RigProviderConfig config,
  required String systemPrompt,
  required List<RigChatMessage> history,
  required List<RigToolDef> tools,
  required int maxTurns,
  required FutureOr<String> Function(String, String) toolDispatch,
}) => RustLib.instance.api.crateApiAssistantRigChatStream(
  config: config,
  systemPrompt: systemPrompt,
  history: history,
  tools: tools,
  maxTurns: maxTurns,
  toolDispatch: toolDispatch,
);

class RigChatMessage {
  /// `"user"` 或 `"assistant"`。
  final String role;
  final String content;

  const RigChatMessage({required this.role, required this.content});

  @override
  int get hashCode => role.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RigChatMessage &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          content == other.content;
}

/// 用「plain enum + 载荷字段」而非带数据的枚举变体，是为了让 FRB 生成普通 Dart
/// 类 / 枚举，避开它对 `freezed`（项目当前钉在 pre-release 版）的版本门槛。
enum RigEventKind { textDelta, toolCall }

/// 一次对话的 provider 连接配置。每次调用由 Dart 组装传入，Rust 不持有任何状态。
class RigProviderConfig {
  /// `"openai"`（OpenAI 兼容，走 Chat Completions API）或 `"anthropic"`。
  final String protocol;
  final String apiKey;

  /// 自定义 baseUrl，留空表示该协议官方端点。
  final String baseUrl;
  final String model;

  /// 单次回复最大 token 数（Anthropic 协议必传）。
  final int maxTokens;

  const RigProviderConfig({
    required this.protocol,
    required this.apiKey,
    required this.baseUrl,
    required this.model,
    required this.maxTokens,
  });

  @override
  int get hashCode =>
      protocol.hashCode ^
      apiKey.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      maxTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RigProviderConfig &&
          runtimeType == other.runtimeType &&
          protocol == other.protocol &&
          apiKey == other.apiKey &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          maxTokens == other.maxTokens;
}

class RigStreamEvent {
  final RigEventKind kind;
  final String text;

  const RigStreamEvent({required this.kind, required this.text});

  @override
  int get hashCode => kind.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RigStreamEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          text == other.text;
}

/// 工具定义（数据驱动，对应 Dart 的 `AssistantTool`）。
class RigToolDef {
  /// 模型侧 function name，须与 Dart 工具路由表里的 key 一致。
  final String name;
  final String description;

  /// 入参 JSON Schema（字符串，须是 `type: object`）。
  final String parametersJson;

  const RigToolDef({
    required this.name,
    required this.description,
    required this.parametersJson,
  });

  @override
  int get hashCode =>
      name.hashCode ^ description.hashCode ^ parametersJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RigToolDef &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          parametersJson == other.parametersJson;
}
