// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Dart 取消订阅会令 `sink.add` 失败，循环随即中断并取消在途请求。
Stream<RigStreamEvent> rigChatStream({
  required RigProviderConfig config,
  required String systemPrompt,
  required List<RigChatMessage> history,
  required List<RigToolDef> tools,
  required int maxTurns,
  required FutureOr<String> Function(String, String) toolDispatch,
}) => RustLib.instance.api.crateApiAssistantRigChatStream(
  config: config,
  systemPrompt: systemPrompt,
  history: history,
  tools: tools,
  maxTurns: maxTurns,
  toolDispatch: toolDispatch,
);

class RigChatMessage {
  /// `"user"` 或 `"assistant"`。
  final String role;
  final String content;

  /// base64，不含 data URL 前缀。空表示无图；仅 user 消息使用。
  final String imageBase64;
  final String imageMime;

  const RigChatMessage({
    required this.role,
    required this.content,
    required this.imageBase64,
    required this.imageMime,
  });

  @override
  int get hashCode =>
      role.hashCode ^
      content.hashCode ^
      imageBase64.hashCode ^
      imageMime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RigChatMessage &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          content == other.content &&
          imageBase64 == other.imageBase64 &&
          imageMime == other.imageMime;
}

/// 用「plain enum + 载荷字段」而非带数据的枚举变体，是为了让 FRB 生成普通 Dart
/// 类，避开它对 freezed（项目当前钉在 pre-release 版）的版本门槛。
enum RigEventKind { textDelta, reasoningDelta, toolCall, usage }

class RigProviderConfig {
  /// `"openai"`（OpenAI 兼容，走 Chat Completions）或 `"anthropic"`。
  final String protocol;
  final String apiKey;

  /// 留空表示该协议官方端点。
  final String baseUrl;
  final String model;
  final int maxTokens;

  /// rig 不会自动开启思考，开启后由 Rust 按协议注入参数：Anthropic 走 extended
  /// thinking，OpenAI 兼容走 `reasoning_effort: "medium"`。
  final bool thinking;

  const RigProviderConfig({
    required this.protocol,
    required this.apiKey,
    required this.baseUrl,
    required this.model,
    required this.maxTokens,
    required this.thinking,
  });

  @override
  int get hashCode =>
      protocol.hashCode ^
      apiKey.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      maxTokens.hashCode ^
      thinking.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RigProviderConfig &&
          runtimeType == other.runtimeType &&
          protocol == other.protocol &&
          apiKey == other.apiKey &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          maxTokens == other.maxTokens &&
          thinking == other.thinking;
}

class RigStreamEvent {
  final RigEventKind kind;
  final String text;

  /// 仅 [RigEventKind::Usage] 事件有意义，其余为 0。
  final int inputTokens;
  final int outputTokens;

  const RigStreamEvent({
    required this.kind,
    required this.text,
    required this.inputTokens,
    required this.outputTokens,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      text.hashCode ^
      inputTokens.hashCode ^
      outputTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RigStreamEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          text == other.text &&
          inputTokens == other.inputTokens &&
          outputTokens == other.outputTokens;
}

class RigToolDef {
  /// 须与 Dart 工具路由表里的 key 一致。
  final String name;
  final String description;

  /// 入参 JSON Schema（字符串，须是 `type: object`）。FRB 的 serde_json::Value 只支持
  /// 函数参数/返回值，放进 mirror 结构体字段会缺 IntoIntoDart，所以这里仍走字符串。
  final String parametersJson;

  const RigToolDef({
    required this.name,
    required this.description,
    required this.parametersJson,
  });

  @override
  int get hashCode =>
      name.hashCode ^ description.hashCode ^ parametersJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RigToolDef &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          parametersJson == other.parametersJson;
}
