// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Aes>>
abstract class Aes implements RustOpaqueInterface {
  static Future<Uint8List> decrypt({
    required List<int> key,
    required List<int> encryptedData,
  }) => RustLib.instance.api.crateApiCryptoAesDecrypt(
    key: key,
    encryptedData: encryptedData,
  );

  /// [skip_prefix] = 写入时 prefix 的字节数。
  static Future<void> decryptFile({
    required List<int> key,
    required String inPath,
    required String outPath,
    required BigInt skipPrefix,
  }) => RustLib.instance.api.crateApiCryptoAesDecryptFile(
    key: key,
    inPath: inPath,
    outPath: outPath,
    skipPrefix: skipPrefix,
  );

  static Future<Uint8List> deriveKey({
    required String salt,
    required String userKey,
    int? mCostKib,
    int? tCost,
    int? pCost,
  }) => RustLib.instance.api.crateApiCryptoAesDeriveKey(
    salt: salt,
    userKey: userKey,
    mCostKib: mCostKib,
    tCost: tCost,
    pCost: pCost,
  );

  static Future<Uint8List> encrypt({
    required List<int> key,
    required List<int> data,
  }) => RustLib.instance.api.crateApiCryptoAesEncrypt(key: key, data: data);

  /// 文件到文件，明文密文都不过桥。[prefix] 原样写在最前面（同步层的 magic 头）。
  /// 字节布局与 [Self::encrypt] 一致，两条路互通。
  static Future<void> encryptFile({
    required List<int> key,
    required String inPath,
    required String outPath,
    required List<int> prefix,
  }) => RustLib.instance.api.crateApiCryptoAesEncryptFile(
    key: key,
    inPath: inPath,
    outPath: outPath,
    prefix: prefix,
  );
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Argon2>>
abstract class Argon2 implements RustOpaqueInterface {
  static Future<String> hash({required String password}) =>
      RustLib.instance.api.crateApiCryptoArgon2Hash(password: password);

  static Future<bool> verify({
    required String hash,
    required String password,
  }) => RustLib.instance.api.crateApiCryptoArgon2Verify(
    hash: hash,
    password: password,
  );
}
