// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'http.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fallback_response`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HttpServer>>
abstract class HttpServer implements RustOpaqueInterface {
  int port();

  static Future<HttpServer> start({
    required int preferredPort,
    required bool loopbackOnly,
    required String spoolDir,
    required FutureOr<HttpServerResponse> Function(HttpServerRequest) onRequest,
    required FutureOr<void> Function(PlatformInt64, PlatformInt64)
    onBodyProgress,
  }) => RustLib.instance.api.crateApiHttpServerHttpServerStart(
    preferredPort: preferredPort,
    loopbackOnly: loopbackOnly,
    spoolDir: spoolDir,
    onRequest: onRequest,
    onBodyProgress: onBodyProgress,
  );

  void stop();
}

class HttpServerRequest {
  final String method;
  final String path;
  final List<KeyValue> query;
  final List<KeyValue> headers;

  /// 小请求体内联；已落盘时为空、见 [Self::body_file_path]。
  final Uint8List body;

  /// 大请求体流式落盘的临时文件。仅在 handler 执行期间有效，返回后由服务器删除。
  final String? bodyFilePath;

  const HttpServerRequest({
    required this.method,
    required this.path,
    required this.query,
    required this.headers,
    required this.body,
    this.bodyFilePath,
  });

  @override
  int get hashCode =>
      method.hashCode ^
      path.hashCode ^
      query.hashCode ^
      headers.hashCode ^
      body.hashCode ^
      bodyFilePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpServerRequest &&
          runtimeType == other.runtimeType &&
          method == other.method &&
          path == other.path &&
          query == other.query &&
          headers == other.headers &&
          body == other.body &&
          bodyFilePath == other.bodyFilePath;
}

/// handler 返回的响应。[Self::body_file_path] 非空时从磁盘流式发送并自动支持
/// Range（此时 [Self::body] 被忽略）。
class HttpServerResponse {
  final int status;
  final List<KeyValue> headers;
  final Uint8List body;
  final String? bodyFilePath;

  const HttpServerResponse({
    required this.status,
    required this.headers,
    required this.body,
    this.bodyFilePath,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      headers.hashCode ^
      body.hashCode ^
      bodyFilePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpServerResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          headers == other.headers &&
          body == other.body &&
          bodyFilePath == other.bodyFilePath;
}
