// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `calculate_target_dimensions`, `compress`, `prepare`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ResizeOptions`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `eq`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ImageCompressor>>
abstract class ImageCompressor implements RustOpaqueInterface {
  static Future<void> containToFile({
    required String filePath,
    required String outputPath,
    required CompressSpec spec,
  }) => RustLib.instance.api.crateApiImageImageCompressorContainToFile(
    filePath: filePath,
    outputPath: outputPath,
    spec: spec,
  );
}

enum CompressFormat { jpeg, webP, png }

class CompressSpec {
  final CompressFormat? compressFormat;
  final int? targetWidth;
  final int? targetHeight;
  final int? minWidth;
  final int? minHeight;
  final int? maxWidth;
  final int? maxHeight;
  final int? quality;

  const CompressSpec({
    this.compressFormat,
    this.targetWidth,
    this.targetHeight,
    this.minWidth,
    this.minHeight,
    this.maxWidth,
    this.maxHeight,
    this.quality,
  });

  @override
  int get hashCode =>
      compressFormat.hashCode ^
      targetWidth.hashCode ^
      targetHeight.hashCode ^
      minWidth.hashCode ^
      minHeight.hashCode ^
      maxWidth.hashCode ^
      maxHeight.hashCode ^
      quality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompressSpec &&
          runtimeType == other.runtimeType &&
          compressFormat == other.compressFormat &&
          targetWidth == other.targetWidth &&
          targetHeight == other.targetHeight &&
          minWidth == other.minWidth &&
          minHeight == other.minHeight &&
          maxWidth == other.maxWidth &&
          maxHeight == other.maxHeight &&
          quality == other.quality;
}
