// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 随机 UUID v4，小写带连字符，与 Dart `package:uuid` 输出格式一致。
String uuidV4() => RustLib.instance.api.crateApiUuidUuidV4();

/// 基于当前时间的 UUID v7，前 48 位为毫秒时间戳（可按时间排序，
/// Dart 侧 `MediaUtil.extractDateFromUUID` 依赖此布局）。
String uuidV7() => RustLib.instance.api.crateApiUuidUuidV7();
