// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DavClient>>
abstract class DavClient implements RustOpaqueInterface {
  Future<bool> createExclusive({required String key, required List<int> data});

  Future<void> deleteObject({required String key});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DavClient> newInstance({
    required String baseUrl,
    required String username,
    required String password,
  }) => RustLib.instance.api.crateApiWebdavDavClientNew(
    baseUrl: baseUrl,
    username: username,
    password: password,
  );

  Future<Uint8List?> readObject({required String key});

  Future<bool> readObjectToFile({
    required String key,
    required String filePath,
  });

  Future<String> statObject({required String key});

  Future<bool> testConnection();

  Future<void> writeObject({required String key, required List<int> data});

  Future<void> writeObjectFile({required String key, required String filePath});
}
