// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Zip>>
abstract class Zip implements RustOpaqueInterface {
  /// 内存字节直接写入条目，免落地临时文件。
  Future<void> addBytes({
    required String zipPath,
    required List<int> data,
    String? password,
  });

  Future<void> addDir({
    required String dirPath,
    required String basePath,
    String? password,
  });

  /// [stored] 为 true 时不压缩直接存储（媒体等已压缩格式），并允许单文件 >= 4GiB。
  Future<void> addFile({
    required String filePath,
    required String zipPath,
    String? password,
    bool? stored,
  });

  static Future<void> extract({
    required String zipPath,
    required String destDir,
    String? password,
  }) => RustLib.instance.api.crateApiZipZipExtract(
    zipPath: zipPath,
    destDir: destDir,
    password: password,
  );

  Future<void> finish();

  factory Zip({required String filePath}) =>
      RustLib.instance.api.crateApiZipZipNew(filePath: filePath);
}
