// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use crate::api::image::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = DcoCodec,
    default_rust_opaque = RustOpaqueNom,
    default_rust_auto_opaque = RustAutoOpaqueNom,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -2110393147;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__image__FastImageCodec_contain_to_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    file_path: impl CstDecode<String>,
    output_path: impl CstDecode<String>,
    spec: impl CstDecode<crate::api::image::FastCompressSpec>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "FastImageCodec_contain_to_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_file_path = file_path.cst_decode();
            let api_output_path = output_path.cst_decode();
            let api_spec = spec.cst_decode();
            move |context| {
                transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::image::FastImageCodec::contain_to_file(
                            api_file_path,
                            api_output_path,
                            api_spec,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__image__FastImageCodec_make_thumbnails_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    file_path: impl CstDecode<String>,
    targets: impl CstDecode<Vec<crate::api::image::FastThumbnailTarget>>,
    quality: impl CstDecode<Option<u8>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "FastImageCodec_make_thumbnails",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_file_path = file_path.cst_decode();
            let api_targets = targets.cst_decode();
            let api_quality = quality.cst_decode();
            move |context| {
                transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::image::FastImageCodec::make_thumbnails(
                            api_file_path,
                            api_targets,
                            api_quality,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__image__FastImageCodec_probe_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    file_path: impl CstDecode<String>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "FastImageCodec_probe",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_file_path = file_path.cst_decode();
            move |context| {
                transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::image::FastImageCodec::probe(api_file_path)?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__image__FastImageCodec_to_baseline_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    file_path: impl CstDecode<String>,
    output_path: impl CstDecode<String>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "FastImageCodec_to_baseline_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_file_path = file_path.cst_decode();
            let api_output_path = output_path.cst_decode();
            move |context| {
                transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::image::FastImageCodec::to_baseline_file(
                            api_file_path,
                            api_output_path,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__image__FastRegionDecoder_decode_tile_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<
        RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastRegionDecoder>>,
    >,
    x: impl CstDecode<u32>,
    y: impl CstDecode<u32>,
    width: impl CstDecode<u32>,
    height: impl CstDecode<u32>,
    denom: impl CstDecode<u8>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "FastRegionDecoder_decode_tile",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            let api_x = x.cst_decode();
            let api_y = y.cst_decode();
            let api_width = width.cst_decode();
            let api_height = height.cst_decode();
            let api_denom = denom.cst_decode();
            move |context| {
                transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let mut api_that_guard = None;
                        let decode_indices_ =
                            flutter_rust_bridge::for_generated::lockable_compute_decode_order(
                                vec![flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                    &api_that, 0, false,
                                )],
                            );
                        for i in decode_indices_ {
                            match i {
                                0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                                _ => unreachable!(),
                            }
                        }
                        let api_that_guard = api_that_guard.unwrap();
                        let output_ok = crate::api::image::FastRegionDecoder::decode_tile(
                            &*api_that_guard,
                            api_x,
                            api_y,
                            api_width,
                            api_height,
                            api_denom,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__image__FastRegionDecoder_decode_tiles_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<
        RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastRegionDecoder>>,
    >,
    rects: impl CstDecode<Vec<crate::api::image::FastTileRect>>,
    denom: impl CstDecode<u8>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "FastRegionDecoder_decode_tiles",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            let api_rects = rects.cst_decode();
            let api_denom = denom.cst_decode();
            move |context| {
                transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let mut api_that_guard = None;
                        let decode_indices_ =
                            flutter_rust_bridge::for_generated::lockable_compute_decode_order(
                                vec![flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                    &api_that, 0, false,
                                )],
                            );
                        for i in decode_indices_ {
                            match i {
                                0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                                _ => unreachable!(),
                            }
                        }
                        let api_that_guard = api_that_guard.unwrap();
                        let output_ok = crate::api::image::FastRegionDecoder::decode_tiles(
                            &*api_that_guard,
                            api_rects,
                            api_denom,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__image__FastRegionDecoder_open_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    file_path: impl CstDecode<String>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "FastRegionDecoder_open",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_file_path = file_path.cst_decode();
            move |context| {
                transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::image::FastRegionDecoder::open(api_file_path)?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__image__FastRegionDecoder_probe_impl(
    that: impl CstDecode<
        RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastRegionDecoder>>,
    >,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "FastRegionDecoder_probe",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_that = that.cst_decode();
            transform_result_dco::<_, _, ()>((move || {
                let mut api_that_guard = None;
                let decode_indices_ =
                    flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                        flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                            &api_that, 0, false,
                        ),
                    ]);
                for i in decode_indices_ {
                    match i {
                        0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                        _ => unreachable!(),
                    }
                }
                let api_that_guard = api_that_guard.unwrap();
                let output_ok = Ok::<_, ()>(crate::api::image::FastRegionDecoder::probe(
                    &*api_that_guard,
                ))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__image__FastRegionDecoder_random_access_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<
        RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastRegionDecoder>>,
    >,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "FastRegionDecoder_random_access",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let mut api_that_guard = None;
                    let decode_indices_ =
                        flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                            flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                &api_that, 0, false,
                            ),
                        ]);
                    for i in decode_indices_ {
                        match i {
                            0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                            _ => unreachable!(),
                        }
                    }
                    let api_that_guard = api_that_guard.unwrap();
                    let output_ok = Ok::<_, ()>(
                        crate::api::image::FastRegionDecoder::random_access(&*api_that_guard),
                    )?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}

// Section: static_checks

#[allow(clippy::unnecessary_literal_unwrap)]
const _: fn() = || {
    {
        let FastCompressSpec = None::<crate::api::image::FastCompressSpec>.unwrap();
        let _: Option<crate::api::image::FastCompressFormat> = FastCompressSpec.compress_format;
        let _: Option<u32> = FastCompressSpec.target_width;
        let _: Option<u32> = FastCompressSpec.target_height;
        let _: Option<u32> = FastCompressSpec.min_width;
        let _: Option<u32> = FastCompressSpec.min_height;
        let _: Option<u32> = FastCompressSpec.max_width;
        let _: Option<u32> = FastCompressSpec.max_height;
        let _: Option<u8> = FastCompressSpec.quality;
    }
    {
        let FastImageMeta = None::<crate::api::image::FastImageMeta>.unwrap();
        let _: u32 = FastImageMeta.width;
        let _: u32 = FastImageMeta.height;
        let _: String = FastImageMeta.ext;
    }
    {
        let FastImageProbe = None::<crate::api::image::FastImageProbe>.unwrap();
        let _: crate::api::image::FastImageFormat = FastImageProbe.format;
        let _: u32 = FastImageProbe.width;
        let _: u32 = FastImageProbe.height;
        let _: bool = FastImageProbe.progressive;
        let _: bool = FastImageProbe.region_decodable;
    }
    {
        let FastThumbnailTarget = None::<crate::api::image::FastThumbnailTarget>.unwrap();
        let _: u32 = FastThumbnailTarget.width;
        let _: String = FastThumbnailTarget.output_stem;
    }
    {
        let FastTilePixels = None::<crate::api::image::FastTilePixels>.unwrap();
        let _: u32 = FastTilePixels.x;
        let _: u32 = FastTilePixels.y;
        let _: u32 = FastTilePixels.width;
        let _: u32 = FastTilePixels.height;
        let _: u32 = FastTilePixels.pixel_width;
        let _: u32 = FastTilePixels.pixel_height;
        let _: Vec<u8> = FastTilePixels.rgba;
    }
};

// Section: dart2rust

impl CstDecode<bool> for bool {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> bool {
        self
    }
}
impl CstDecode<crate::api::image::FastCompressFormat> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::image::FastCompressFormat {
        match self {
            0 => crate::api::image::FastCompressFormat::Jpeg,
            1 => crate::api::image::FastCompressFormat::Png,
            _ => unreachable!("Invalid variant for FastCompressFormat: {}", self),
        }
    }
}
impl CstDecode<crate::api::image::FastImageFormat> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::image::FastImageFormat {
        match self {
            0 => crate::api::image::FastImageFormat::Jpeg,
            1 => crate::api::image::FastImageFormat::Png,
            2 => crate::api::image::FastImageFormat::WebP,
            3 => crate::api::image::FastImageFormat::Gif,
            4 => crate::api::image::FastImageFormat::Bmp,
            5 => crate::api::image::FastImageFormat::Other,
            _ => unreachable!("Invalid variant for FastImageFormat: {}", self),
        }
    }
}
impl CstDecode<i32> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> i32 {
        self
    }
}
impl CstDecode<u32> for u32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u32 {
        self
    }
}
impl CstDecode<u8> for u8 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u8 {
        self
    }
}
impl CstDecode<usize> for usize {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> usize {
        self
    }
}
impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for FastImageCodec {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <RustOpaqueNom<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastImageCodec>,
        >>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
    }
}

impl SseDecode for FastRegionDecoder {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <RustOpaqueNom<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastRegionDecoder>,
        >>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
    }
}

impl SseDecode
    for RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastImageCodec>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return unsafe { decode_rust_opaque_nom(inner) };
    }
}

impl SseDecode
    for RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastRegionDecoder>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return unsafe { decode_rust_opaque_nom(inner) };
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::image::FastCompressFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::image::FastCompressFormat::Jpeg,
            1 => crate::api::image::FastCompressFormat::Png,
            _ => unreachable!("Invalid variant for FastCompressFormat: {}", inner),
        };
    }
}

impl SseDecode for crate::api::image::FastCompressSpec {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_compressFormat =
            <Option<crate::api::image::FastCompressFormat>>::sse_decode(deserializer);
        let mut var_targetWidth = <Option<u32>>::sse_decode(deserializer);
        let mut var_targetHeight = <Option<u32>>::sse_decode(deserializer);
        let mut var_minWidth = <Option<u32>>::sse_decode(deserializer);
        let mut var_minHeight = <Option<u32>>::sse_decode(deserializer);
        let mut var_maxWidth = <Option<u32>>::sse_decode(deserializer);
        let mut var_maxHeight = <Option<u32>>::sse_decode(deserializer);
        let mut var_quality = <Option<u8>>::sse_decode(deserializer);
        return crate::api::image::FastCompressSpec {
            compress_format: var_compressFormat,
            target_width: var_targetWidth,
            target_height: var_targetHeight,
            min_width: var_minWidth,
            min_height: var_minHeight,
            max_width: var_maxWidth,
            max_height: var_maxHeight,
            quality: var_quality,
        };
    }
}

impl SseDecode for crate::api::image::FastImageFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::image::FastImageFormat::Jpeg,
            1 => crate::api::image::FastImageFormat::Png,
            2 => crate::api::image::FastImageFormat::WebP,
            3 => crate::api::image::FastImageFormat::Gif,
            4 => crate::api::image::FastImageFormat::Bmp,
            5 => crate::api::image::FastImageFormat::Other,
            _ => unreachable!("Invalid variant for FastImageFormat: {}", inner),
        };
    }
}

impl SseDecode for crate::api::image::FastImageMeta {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        let mut var_ext = <String>::sse_decode(deserializer);
        return crate::api::image::FastImageMeta {
            width: var_width,
            height: var_height,
            ext: var_ext,
        };
    }
}

impl SseDecode for crate::api::image::FastImageProbe {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_format = <crate::api::image::FastImageFormat>::sse_decode(deserializer);
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        let mut var_progressive = <bool>::sse_decode(deserializer);
        let mut var_regionDecodable = <bool>::sse_decode(deserializer);
        return crate::api::image::FastImageProbe {
            format: var_format,
            width: var_width,
            height: var_height,
            progressive: var_progressive,
            region_decodable: var_regionDecodable,
        };
    }
}

impl SseDecode for crate::api::image::FastThumbnailTarget {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_outputStem = <String>::sse_decode(deserializer);
        return crate::api::image::FastThumbnailTarget {
            width: var_width,
            output_stem: var_outputStem,
        };
    }
}

impl SseDecode for crate::api::image::FastTilePixels {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_x = <u32>::sse_decode(deserializer);
        let mut var_y = <u32>::sse_decode(deserializer);
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        let mut var_pixelWidth = <u32>::sse_decode(deserializer);
        let mut var_pixelHeight = <u32>::sse_decode(deserializer);
        let mut var_rgba = <Vec<u8>>::sse_decode(deserializer);
        return crate::api::image::FastTilePixels {
            x: var_x,
            y: var_y,
            width: var_width,
            height: var_height,
            pixel_width: var_pixelWidth,
            pixel_height: var_pixelHeight,
            rgba: var_rgba,
        };
    }
}

impl SseDecode for crate::api::image::FastTileRect {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_x = <u32>::sse_decode(deserializer);
        let mut var_y = <u32>::sse_decode(deserializer);
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        return crate::api::image::FastTileRect {
            x: var_x,
            y: var_y,
            width: var_width,
            height: var_height,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::image::FastThumbnailTarget> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::image::FastThumbnailTarget>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::image::FastTilePixels> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::image::FastTilePixels>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::image::FastTileRect> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::image::FastTileRect>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<crate::api::image::FastCompressFormat> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::image::FastCompressFormat>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u8>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<FastImageCodec> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, StdArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<FastImageCodec> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<FastImageCodec>> for FastImageCodec {
    fn into_into_dart(self) -> FrbWrapper<FastImageCodec> {
        self.into()
    }
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<FastRegionDecoder> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, StdArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<FastRegionDecoder> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<FastRegionDecoder>> for FastRegionDecoder {
    fn into_into_dart(self) -> FrbWrapper<FastRegionDecoder> {
        self.into()
    }
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::image::FastCompressFormat> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self.0 {
            crate::api::image::FastCompressFormat::Jpeg => 0.into_dart(),
            crate::api::image::FastCompressFormat::Png => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::image::FastCompressFormat>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::image::FastCompressFormat>>
    for crate::api::image::FastCompressFormat
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::image::FastCompressFormat> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::image::FastCompressSpec> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.compress_format.into_into_dart().into_dart(),
            self.0.target_width.into_into_dart().into_dart(),
            self.0.target_height.into_into_dart().into_dart(),
            self.0.min_width.into_into_dart().into_dart(),
            self.0.min_height.into_into_dart().into_dart(),
            self.0.max_width.into_into_dart().into_dart(),
            self.0.max_height.into_into_dart().into_dart(),
            self.0.quality.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::image::FastCompressSpec>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::image::FastCompressSpec>>
    for crate::api::image::FastCompressSpec
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::image::FastCompressSpec> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::image::FastImageFormat> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self.0 {
            crate::api::image::FastImageFormat::Jpeg => 0.into_dart(),
            crate::api::image::FastImageFormat::Png => 1.into_dart(),
            crate::api::image::FastImageFormat::WebP => 2.into_dart(),
            crate::api::image::FastImageFormat::Gif => 3.into_dart(),
            crate::api::image::FastImageFormat::Bmp => 4.into_dart(),
            crate::api::image::FastImageFormat::Other => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::image::FastImageFormat>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::image::FastImageFormat>>
    for crate::api::image::FastImageFormat
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::image::FastImageFormat> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::image::FastImageMeta> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.width.into_into_dart().into_dart(),
            self.0.height.into_into_dart().into_dart(),
            self.0.ext.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::image::FastImageMeta>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::image::FastImageMeta>>
    for crate::api::image::FastImageMeta
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::image::FastImageMeta> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::image::FastImageProbe> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.format.into_into_dart().into_dart(),
            self.0.width.into_into_dart().into_dart(),
            self.0.height.into_into_dart().into_dart(),
            self.0.progressive.into_into_dart().into_dart(),
            self.0.region_decodable.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::image::FastImageProbe>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::image::FastImageProbe>>
    for crate::api::image::FastImageProbe
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::image::FastImageProbe> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::image::FastThumbnailTarget> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.width.into_into_dart().into_dart(),
            self.0.output_stem.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::image::FastThumbnailTarget>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::image::FastThumbnailTarget>>
    for crate::api::image::FastThumbnailTarget
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::image::FastThumbnailTarget> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::image::FastTilePixels> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.x.into_into_dart().into_dart(),
            self.0.y.into_into_dart().into_dart(),
            self.0.width.into_into_dart().into_dart(),
            self.0.height.into_into_dart().into_dart(),
            self.0.pixel_width.into_into_dart().into_dart(),
            self.0.pixel_height.into_into_dart().into_dart(),
            self.0.rgba.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::image::FastTilePixels>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::image::FastTilePixels>>
    for crate::api::image::FastTilePixels
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::image::FastTilePixels> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image::FastTileRect {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.x.into_into_dart().into_dart(),
            self.y.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image::FastTileRect
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image::FastTileRect>
    for crate::api::image::FastTileRect
{
    fn into_into_dart(self) -> crate::api::image::FastTileRect {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for FastImageCodec {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastImageCodec>>>::sse_encode(flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, StdArc<_>>(self), serializer);
    }
}

impl SseEncode for FastRegionDecoder {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastRegionDecoder>>>::sse_encode(flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, StdArc<_>>(self), serializer);
    }
}

impl SseEncode
    for RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastImageCodec>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode
    for RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastRegionDecoder>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::image::FastCompressFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::image::FastCompressFormat::Jpeg => 0,
                crate::api::image::FastCompressFormat::Png => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::image::FastCompressSpec {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<crate::api::image::FastCompressFormat>>::sse_encode(
            self.compress_format,
            serializer,
        );
        <Option<u32>>::sse_encode(self.target_width, serializer);
        <Option<u32>>::sse_encode(self.target_height, serializer);
        <Option<u32>>::sse_encode(self.min_width, serializer);
        <Option<u32>>::sse_encode(self.min_height, serializer);
        <Option<u32>>::sse_encode(self.max_width, serializer);
        <Option<u32>>::sse_encode(self.max_height, serializer);
        <Option<u8>>::sse_encode(self.quality, serializer);
    }
}

impl SseEncode for crate::api::image::FastImageFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::image::FastImageFormat::Jpeg => 0,
                crate::api::image::FastImageFormat::Png => 1,
                crate::api::image::FastImageFormat::WebP => 2,
                crate::api::image::FastImageFormat::Gif => 3,
                crate::api::image::FastImageFormat::Bmp => 4,
                crate::api::image::FastImageFormat::Other => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::image::FastImageMeta {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
        <String>::sse_encode(self.ext, serializer);
    }
}

impl SseEncode for crate::api::image::FastImageProbe {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::image::FastImageFormat>::sse_encode(self.format, serializer);
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
        <bool>::sse_encode(self.progressive, serializer);
        <bool>::sse_encode(self.region_decodable, serializer);
    }
}

impl SseEncode for crate::api::image::FastThumbnailTarget {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.width, serializer);
        <String>::sse_encode(self.output_stem, serializer);
    }
}

impl SseEncode for crate::api::image::FastTilePixels {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.x, serializer);
        <u32>::sse_encode(self.y, serializer);
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
        <u32>::sse_encode(self.pixel_width, serializer);
        <u32>::sse_encode(self.pixel_height, serializer);
        <Vec<u8>>::sse_encode(self.rgba, serializer);
    }
}

impl SseEncode for crate::api::image::FastTileRect {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.x, serializer);
        <u32>::sse_encode(self.y, serializer);
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::image::FastThumbnailTarget> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::image::FastThumbnailTarget>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::image::FastTilePixels> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::image::FastTilePixels>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::image::FastTileRect> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::image::FastTileRect>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::image::FastCompressFormat> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::image::FastCompressFormat>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u8>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use crate::api::image::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    // Section: dart2rust

    impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error>
        for *mut wire_cst_list_prim_u_8_strict
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
            unimplemented!()
        }
    }
    impl CstDecode<FastImageCodec> for usize {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> FastImageCodec {
            flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
                RustOpaqueNom<
                    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastImageCodec>,
                >,
            >::cst_decode(
                self
            ))
        }
    }
    impl CstDecode<FastRegionDecoder> for usize {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> FastRegionDecoder {
            flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
                RustOpaqueNom<
                    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastRegionDecoder>,
                >,
            >::cst_decode(
                self
            ))
        }
    }
    impl
        CstDecode<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastImageCodec>>,
        > for usize
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(
            self,
        ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastImageCodec>>
        {
            unsafe { decode_rust_opaque_nom(self as _) }
        }
    }
    impl
        CstDecode<
            RustOpaqueNom<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastRegionDecoder>,
            >,
        > for usize
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(
            self,
        ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastRegionDecoder>>
        {
            unsafe { decode_rust_opaque_nom(self as _) }
        }
    }
    impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            let vec: Vec<u8> = self.cst_decode();
            String::from_utf8(vec).unwrap()
        }
    }
    impl CstDecode<crate::api::image::FastCompressFormat> for *mut i32 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::image::FastCompressFormat {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::image::FastCompressFormat>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<crate::api::image::FastCompressSpec> for *mut wire_cst_fast_compress_spec {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::image::FastCompressSpec {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::image::FastCompressSpec>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<u32> for *mut u32 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u32 {
            unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
        }
    }
    impl CstDecode<u8> for *mut u8 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u8 {
            unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
        }
    }
    impl CstDecode<crate::api::image::FastCompressSpec> for wire_cst_fast_compress_spec {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::image::FastCompressSpec {
            crate::api::image::FastCompressSpec {
                compress_format: self.compress_format.cst_decode(),
                target_width: self.target_width.cst_decode(),
                target_height: self.target_height.cst_decode(),
                min_width: self.min_width.cst_decode(),
                min_height: self.min_height.cst_decode(),
                max_width: self.max_width.cst_decode(),
                max_height: self.max_height.cst_decode(),
                quality: self.quality.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::image::FastImageMeta> for wire_cst_fast_image_meta {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::image::FastImageMeta {
            crate::api::image::FastImageMeta {
                width: self.width.cst_decode(),
                height: self.height.cst_decode(),
                ext: self.ext.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::image::FastImageProbe> for wire_cst_fast_image_probe {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::image::FastImageProbe {
            crate::api::image::FastImageProbe {
                format: self.format.cst_decode(),
                width: self.width.cst_decode(),
                height: self.height.cst_decode(),
                progressive: self.progressive.cst_decode(),
                region_decodable: self.region_decodable.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::image::FastThumbnailTarget> for wire_cst_fast_thumbnail_target {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::image::FastThumbnailTarget {
            crate::api::image::FastThumbnailTarget {
                width: self.width.cst_decode(),
                output_stem: self.output_stem.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::image::FastTilePixels> for wire_cst_fast_tile_pixels {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::image::FastTilePixels {
            crate::api::image::FastTilePixels {
                x: self.x.cst_decode(),
                y: self.y.cst_decode(),
                width: self.width.cst_decode(),
                height: self.height.cst_decode(),
                pixel_width: self.pixel_width.cst_decode(),
                pixel_height: self.pixel_height.cst_decode(),
                rgba: self.rgba.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::image::FastTileRect> for wire_cst_fast_tile_rect {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::image::FastTileRect {
            crate::api::image::FastTileRect {
                x: self.x.cst_decode(),
                y: self.y.cst_decode(),
                width: self.width.cst_decode(),
                height: self.height.cst_decode(),
            }
        }
    }
    impl CstDecode<Vec<crate::api::image::FastThumbnailTarget>>
        for *mut wire_cst_list_fast_thumbnail_target
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::image::FastThumbnailTarget> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<crate::api::image::FastTilePixels>> for *mut wire_cst_list_fast_tile_pixels {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::image::FastTilePixels> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<crate::api::image::FastTileRect>> for *mut wire_cst_list_fast_tile_rect {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::image::FastTileRect> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl NewWithNullPtr for wire_cst_fast_compress_spec {
        fn new_with_null_ptr() -> Self {
            Self {
                compress_format: core::ptr::null_mut(),
                target_width: core::ptr::null_mut(),
                target_height: core::ptr::null_mut(),
                min_width: core::ptr::null_mut(),
                min_height: core::ptr::null_mut(),
                max_width: core::ptr::null_mut(),
                max_height: core::ptr::null_mut(),
                quality: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_fast_compress_spec {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_fast_image_meta {
        fn new_with_null_ptr() -> Self {
            Self {
                width: Default::default(),
                height: Default::default(),
                ext: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_fast_image_meta {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_fast_image_probe {
        fn new_with_null_ptr() -> Self {
            Self {
                format: Default::default(),
                width: Default::default(),
                height: Default::default(),
                progressive: Default::default(),
                region_decodable: Default::default(),
            }
        }
    }
    impl Default for wire_cst_fast_image_probe {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_fast_thumbnail_target {
        fn new_with_null_ptr() -> Self {
            Self {
                width: Default::default(),
                output_stem: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_fast_thumbnail_target {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_fast_tile_pixels {
        fn new_with_null_ptr() -> Self {
            Self {
                x: Default::default(),
                y: Default::default(),
                width: Default::default(),
                height: Default::default(),
                pixel_width: Default::default(),
                pixel_height: Default::default(),
                rgba: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_fast_tile_pixels {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_fast_tile_rect {
        fn new_with_null_ptr() -> Self {
            Self {
                x: Default::default(),
                y: Default::default(),
                width: Default::default(),
                height: Default::default(),
            }
        }
    }
    impl Default for wire_cst_fast_tile_rect {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_wire__crate__api__image__FastImageCodec_contain_to_file(
        port_: i64,
        file_path: *mut wire_cst_list_prim_u_8_strict,
        output_path: *mut wire_cst_list_prim_u_8_strict,
        spec: *mut wire_cst_fast_compress_spec,
    ) {
        wire__crate__api__image__FastImageCodec_contain_to_file_impl(
            port_,
            file_path,
            output_path,
            spec,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_wire__crate__api__image__FastImageCodec_make_thumbnails(
        port_: i64,
        file_path: *mut wire_cst_list_prim_u_8_strict,
        targets: *mut wire_cst_list_fast_thumbnail_target,
        quality: *mut u8,
    ) {
        wire__crate__api__image__FastImageCodec_make_thumbnails_impl(
            port_, file_path, targets, quality,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_wire__crate__api__image__FastImageCodec_probe(
        port_: i64,
        file_path: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__image__FastImageCodec_probe_impl(port_, file_path)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_wire__crate__api__image__FastImageCodec_to_baseline_file(
        port_: i64,
        file_path: *mut wire_cst_list_prim_u_8_strict,
        output_path: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__image__FastImageCodec_to_baseline_file_impl(port_, file_path, output_path)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_wire__crate__api__image__FastRegionDecoder_decode_tile(
        port_: i64,
        that: usize,
        x: u32,
        y: u32,
        width: u32,
        height: u32,
        denom: u8,
    ) {
        wire__crate__api__image__FastRegionDecoder_decode_tile_impl(
            port_, that, x, y, width, height, denom,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_wire__crate__api__image__FastRegionDecoder_decode_tiles(
        port_: i64,
        that: usize,
        rects: *mut wire_cst_list_fast_tile_rect,
        denom: u8,
    ) {
        wire__crate__api__image__FastRegionDecoder_decode_tiles_impl(port_, that, rects, denom)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_wire__crate__api__image__FastRegionDecoder_open(
        port_: i64,
        file_path: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__image__FastRegionDecoder_open_impl(port_, file_path)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_wire__crate__api__image__FastRegionDecoder_probe(
        that: usize,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__image__FastRegionDecoder_probe_impl(that)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_wire__crate__api__image__FastRegionDecoder_random_access(
        port_: i64,
        that: usize,
    ) {
        wire__crate__api__image__FastRegionDecoder_random_access_impl(port_, that)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFastImageCodec(
        ptr: *const std::ffi::c_void,
    ) {
        unsafe {
            StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastImageCodec>>::increment_strong_count(ptr as _);
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFastImageCodec(
        ptr: *const std::ffi::c_void,
    ) {
        unsafe {
            StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastImageCodec>>::decrement_strong_count(ptr as _);
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFastRegionDecoder(
        ptr: *const std::ffi::c_void,
    ) {
        unsafe {
            StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastRegionDecoder>>::increment_strong_count(ptr as _);
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFastRegionDecoder(
        ptr: *const std::ffi::c_void,
    ) {
        unsafe {
            StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastRegionDecoder>>::decrement_strong_count(ptr as _);
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_cst_new_box_autoadd_fast_compress_format(
        value: i32,
    ) -> *mut i32 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_cst_new_box_autoadd_fast_compress_spec()
    -> *mut wire_cst_fast_compress_spec {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_fast_compress_spec::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_cst_new_box_autoadd_u_32(value: u32) -> *mut u32 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_cst_new_box_autoadd_u_8(value: u8) -> *mut u8 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_cst_new_list_fast_thumbnail_target(
        len: i32,
    ) -> *mut wire_cst_list_fast_thumbnail_target {
        let wrap = wire_cst_list_fast_thumbnail_target {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_fast_thumbnail_target>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_cst_new_list_fast_tile_pixels(
        len: i32,
    ) -> *mut wire_cst_list_fast_tile_pixels {
        let wrap = wire_cst_list_fast_tile_pixels {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_fast_tile_pixels>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_cst_new_list_fast_tile_rect(
        len: i32,
    ) -> *mut wire_cst_list_fast_tile_rect {
        let wrap = wire_cst_list_fast_tile_rect {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_fast_tile_rect>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_image_cst_new_list_prim_u_8_strict(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_strict {
        let ans = wire_cst_list_prim_u_8_strict {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_fast_compress_spec {
        compress_format: *mut i32,
        target_width: *mut u32,
        target_height: *mut u32,
        min_width: *mut u32,
        min_height: *mut u32,
        max_width: *mut u32,
        max_height: *mut u32,
        quality: *mut u8,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_fast_image_meta {
        width: u32,
        height: u32,
        ext: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_fast_image_probe {
        format: i32,
        width: u32,
        height: u32,
        progressive: bool,
        region_decodable: bool,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_fast_thumbnail_target {
        width: u32,
        output_stem: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_fast_tile_pixels {
        x: u32,
        y: u32,
        width: u32,
        height: u32,
        pixel_width: u32,
        pixel_height: u32,
        rgba: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_fast_tile_rect {
        x: u32,
        y: u32,
        width: u32,
        height: u32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_fast_thumbnail_target {
        ptr: *mut wire_cst_fast_thumbnail_target,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_fast_tile_pixels {
        ptr: *mut wire_cst_fast_tile_pixels,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_fast_tile_rect {
        ptr: *mut wire_cst_fast_tile_rect,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_strict {
        ptr: *mut u8,
        len: i32,
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
