// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastImageCodec>>
abstract class FastImageCodec implements RustOpaqueInterface {
  /// 导出用：整图转正、按 spec 定尺寸、编成 JPEG / PNG。
  static Future<void> containToFile({
    required String filePath,
    required String outputPath,
    required FastCompressSpec spec,
  }) => FastImageLib.instance.api.crateApiImageFastImageCodecContainToFile(
    filePath: filePath,
    outputPath: outputPath,
    spec: spec,
  );

  /// 一次解码、链式缩出多个宽度档位；不比档位宽的档位跳过不写。派生物后缀按内容定
  /// （`jpg`，带 alpha 的源 `png`），写在返回的 `ext` 里。
  static Future<FastImageMeta> makeThumbnails({
    required String filePath,
    required List<FastThumbnailTarget> targets,
    int? quality,
  }) => FastImageLib.instance.api.crateApiImageFastImageCodecMakeThumbnails(
    filePath: filePath,
    targets: targets,
    quality: quality,
  );

  /// 只读头不解像素：格式、转正后宽高、是否能走 turbojpeg 缩放 / 区域解码。
  static Future<FastImageProbe> probe({required String filePath}) =>
      FastImageLib.instance.api.crateApiImageFastImageCodecProbe(
        filePath: filePath,
      );

  /// progressive JPEG 无损转 baseline（带 restart marker）落盘，给看图页 tile 用；
  /// 超过 64MP 的报错（要整幅系数缓冲）。先写 `.part` 再 rename。
  static Future<void> toBaselineFile({
    required String filePath,
    required String outputPath,
  }) => FastImageLib.instance.api.crateApiImageFastImageCodecToBaselineFile(
    filePath: filePath,
    outputPath: outputPath,
  );
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FastRegionDecoder>>
abstract class FastRegionDecoder implements RustOpaqueInterface {
  /// `x/y/width/height` 是转正后源像素坐标，`denom` 是 1..=8 的缩放分母。
  /// 返回实际覆盖的矩形（对齐 iMCU 后可能比请求大）与转正后的 RGBA。
  Future<FastTilePixels> decodeTile({
    required int x,
    required int y,
    required int width,
    required int height,
    required int denom,
  });

  /// 一批同 denom 的 tile：并集一次解出来当带，再逐块切。视口里的可见 tile 一次全要，
  /// 313MB 的图就只跑一趟熵解码。
  Future<List<FastTilePixels>> decodeTiles({
    required List<FastTileRect> rects,
    required int denom,
  });

  static Future<FastRegionDecoder> open({required String filePath}) =>
      FastImageLib.instance.api.crateApiImageFastRegionDecoderOpen(
        filePath: filePath,
      );

  FastImageProbe probe();

  /// 文件带对齐的 restart marker：tile 只解覆盖它的段、还能并行。第一次调用会扫一遍文件。
  Future<bool> randomAccess();
}

enum FastCompressFormat { jpeg, png }

class FastCompressSpec {
  final FastCompressFormat? compressFormat;
  final int? targetWidth;
  final int? targetHeight;
  final int? minWidth;
  final int? minHeight;
  final int? maxWidth;
  final int? maxHeight;
  final int? quality;

  const FastCompressSpec({
    this.compressFormat,
    this.targetWidth,
    this.targetHeight,
    this.minWidth,
    this.minHeight,
    this.maxWidth,
    this.maxHeight,
    this.quality,
  });

  @override
  int get hashCode =>
      compressFormat.hashCode ^
      targetWidth.hashCode ^
      targetHeight.hashCode ^
      minWidth.hashCode ^
      minHeight.hashCode ^
      maxWidth.hashCode ^
      maxHeight.hashCode ^
      quality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FastCompressSpec &&
          runtimeType == other.runtimeType &&
          compressFormat == other.compressFormat &&
          targetWidth == other.targetWidth &&
          targetHeight == other.targetHeight &&
          minWidth == other.minWidth &&
          minHeight == other.minHeight &&
          maxWidth == other.maxWidth &&
          maxHeight == other.maxHeight &&
          quality == other.quality;
}

enum FastImageFormat { jpeg, png, webP, gif, bmp, other }

class FastImageMeta {
  final int width;
  final int height;
  final String ext;

  const FastImageMeta({
    required this.width,
    required this.height,
    required this.ext,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ ext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FastImageMeta &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          ext == other.ext;
}

class FastImageProbe {
  final FastImageFormat format;
  final int width;
  final int height;
  final bool progressive;
  final bool regionDecodable;

  const FastImageProbe({
    required this.format,
    required this.width,
    required this.height,
    required this.progressive,
    required this.regionDecodable,
  });

  @override
  int get hashCode =>
      format.hashCode ^
      width.hashCode ^
      height.hashCode ^
      progressive.hashCode ^
      regionDecodable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FastImageProbe &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          width == other.width &&
          height == other.height &&
          progressive == other.progressive &&
          regionDecodable == other.regionDecodable;
}

class FastThumbnailTarget {
  final int width;
  final String outputStem;

  const FastThumbnailTarget({required this.width, required this.outputStem});

  @override
  int get hashCode => width.hashCode ^ outputStem.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FastThumbnailTarget &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          outputStem == other.outputStem;
}

class FastTilePixels {
  final int x;
  final int y;
  final int width;
  final int height;
  final int pixelWidth;
  final int pixelHeight;
  final Uint8List rgba;

  const FastTilePixels({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    required this.pixelWidth,
    required this.pixelHeight,
    required this.rgba,
  });

  @override
  int get hashCode =>
      x.hashCode ^
      y.hashCode ^
      width.hashCode ^
      height.hashCode ^
      pixelWidth.hashCode ^
      pixelHeight.hashCode ^
      rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FastTilePixels &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height &&
          pixelWidth == other.pixelWidth &&
          pixelHeight == other.pixelHeight &&
          rgba == other.rgba;
}

/// 转正后源像素坐标里的一个 tile 矩形。
class FastTileRect {
  final int x;
  final int y;
  final int width;
  final int height;

  const FastTileRect({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FastTileRect &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height;
}
