name: moodiary_di
description: "The single get_it instance."
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.13.0"
  flutter: ">=3.47.0"

dependencies:
  get_it: 9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  moodiary_lint: 0.0.1
