// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/cancel.dart';
import 'api/font.dart';
import 'api/graph_layout.dart';
import 'api/zip.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CancelTokenPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FontReaderPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReaderPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ZipPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZipPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  CancelToken
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    dynamic raw,
  );

  @protected
  FontReader
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader(
    dynamic raw,
  );

  @protected
  Zip
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
    dynamic raw,
  );

  @protected
  Zip
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
    dynamic raw,
  );

  @protected
  CancelToken
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    dynamic raw,
  );

  @protected
  Map<String, double> dco_decode_Map_String_f_32_None(dynamic raw);

  @protected
  CancelToken
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    dynamic raw,
  );

  @protected
  FontReader
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader(
    dynamic raw,
  );

  @protected
  Zip
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
    dynamic raw,
  );

  @protected
  RustStreamSink<Float32List> dco_decode_StreamSink_list_prim_f_32_strict_Dco(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  GraphLayoutParams dco_decode_box_autoadd_graph_layout_params(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  GraphLayoutParams dco_decode_graph_layout_params(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, double)> dco_decode_list_record_string_f_32(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  (String, double) dco_decode_record_string_f_32(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  CancelToken
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    SseDeserializer deserializer,
  );

  @protected
  FontReader
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader(
    SseDeserializer deserializer,
  );

  @protected
  Zip
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
    SseDeserializer deserializer,
  );

  @protected
  Zip
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
    SseDeserializer deserializer,
  );

  @protected
  CancelToken
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, double> sse_decode_Map_String_f_32_None(
    SseDeserializer deserializer,
  );

  @protected
  CancelToken
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    SseDeserializer deserializer,
  );

  @protected
  FontReader
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader(
    SseDeserializer deserializer,
  );

  @protected
  Zip
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<Float32List> sse_decode_StreamSink_list_prim_f_32_strict_Dco(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  GraphLayoutParams sse_decode_box_autoadd_graph_layout_params(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  GraphLayoutParams sse_decode_graph_layout_params(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, double)> sse_decode_list_record_string_f_32(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  (String, double) sse_decode_record_string_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
    AnyhowException raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_record_string_f_32> cst_encode_Map_String_f_32_None(
    Map<String, double> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_record_string_f_32(
      raw.entries.map((e) => (e.key, e.value)).toList(),
    );
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
  cst_encode_StreamSink_list_prim_f_32_strict_Dco(
    RustStreamSink<Float32List> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_prim_f_32_strict,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.Bool> cst_encode_box_autoadd_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_bool(cst_encode_bool(raw));
  }

  @protected
  ffi.Pointer<wire_cst_graph_layout_params>
  cst_encode_box_autoadd_graph_layout_params(GraphLayoutParams raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_graph_layout_params();
    cst_api_fill_to_wire_graph_layout_params(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_f_32_loose> cst_encode_list_prim_f_32_loose(
    List<double> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_f_32_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_f_32_strict> cst_encode_list_prim_f_32_strict(
    Float32List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_f_32_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_i_32_loose> cst_encode_list_prim_i_32_loose(
    List<int> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_i_32_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_i_32_strict> cst_encode_list_prim_i_32_strict(
    Int32List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_i_32_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
    List<int> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_record_string_f_32>
  cst_encode_list_record_string_f_32(List<(String, double)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_record_string_f_32(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_record_string_f_32(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Bool> cst_encode_opt_box_autoadd_bool(bool? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_bool(raw);
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_graph_layout_params(
    GraphLayoutParams apiObj,
    ffi.Pointer<wire_cst_graph_layout_params> wireObj,
  ) {
    cst_api_fill_to_wire_graph_layout_params(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_graph_layout_params(
    GraphLayoutParams apiObj,
    wire_cst_graph_layout_params wireObj,
  ) {
    wireObj.iterations = cst_encode_u_32(apiObj.iterations);
    wireObj.theta = cst_encode_f_32(apiObj.theta);
    wireObj.repulsion = cst_encode_f_32(apiObj.repulsion);
    wireObj.spring_length = cst_encode_f_32(apiObj.springLength);
    wireObj.spring_strength = cst_encode_f_32(apiObj.springStrength);
    wireObj.gravity = cst_encode_f_32(apiObj.gravity);
    wireObj.collide_radius = cst_encode_f_32(apiObj.collideRadius);
    wireObj.velocity_decay = cst_encode_f_32(apiObj.velocityDecay);
    wireObj.emit_every = cst_encode_u_32(apiObj.emitEvery);
    wireObj.frame_delay_ms = cst_encode_u_32(apiObj.frameDelayMs);
    wireObj.initial_alpha = cst_encode_f_32(apiObj.initialAlpha);
    wireObj.min_step = cst_encode_f_32(apiObj.minStep);
    wireObj.pinned_count = cst_encode_u_32(apiObj.pinnedCount);
    wireObj.normalize_scale = cst_encode_bool(apiObj.normalizeScale);
  }

  @protected
  void cst_api_fill_to_wire_record_string_f_32(
    (String, double) apiObj,
    wire_cst_record_string_f_32 wireObj,
  ) {
    wireObj.field0 = cst_encode_String(apiObj.$1);
    wireObj.field1 = cst_encode_f_32(apiObj.$2);
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    CancelToken raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader(
    FontReader raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
    Zip raw,
  );

  @protected
  int
  cst_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
    Zip raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    CancelToken raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    CancelToken raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader(
    FontReader raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
    Zip raw,
  );

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_32(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    CancelToken self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader(
    FontReader self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
    Zip self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
    Zip self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    CancelToken self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_f_32_None(
    Map<String, double> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    CancelToken self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader(
    FontReader self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
    Zip self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_prim_f_32_strict_Dco(
    RustStreamSink<Float32List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_graph_layout_params(
    GraphLayoutParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_graph_layout_params(
    GraphLayoutParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_f_32(
    List<(String, double)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_f_32(
    (String, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<ffi.Bool> cst_new_box_autoadd_bool(bool value) {
    return _cst_new_box_autoadd_bool(value);
  }

  late final _cst_new_box_autoadd_boolPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Bool> Function(ffi.Bool)>>(
        'frbgen_moodiary_rust_cst_new_box_autoadd_bool',
      );
  late final _cst_new_box_autoadd_bool = _cst_new_box_autoadd_boolPtr
      .asFunction<ffi.Pointer<ffi.Bool> Function(bool)>();

  ffi.Pointer<wire_cst_graph_layout_params>
  cst_new_box_autoadd_graph_layout_params() {
    return _cst_new_box_autoadd_graph_layout_params();
  }

  late final _cst_new_box_autoadd_graph_layout_paramsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<wire_cst_graph_layout_params> Function()>
      >('frbgen_moodiary_rust_cst_new_box_autoadd_graph_layout_params');
  late final _cst_new_box_autoadd_graph_layout_params =
      _cst_new_box_autoadd_graph_layout_paramsPtr
          .asFunction<ffi.Pointer<wire_cst_graph_layout_params> Function()>();

  ffi.Pointer<wire_cst_list_prim_f_32_loose> cst_new_list_prim_f_32_loose(
    int len,
  ) {
    return _cst_new_list_prim_f_32_loose(len);
  }

  late final _cst_new_list_prim_f_32_loosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_f_32_loose> Function(ffi.Int32)
        >
      >('frbgen_moodiary_rust_cst_new_list_prim_f_32_loose');
  late final _cst_new_list_prim_f_32_loose = _cst_new_list_prim_f_32_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_f_32_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_f_32_strict> cst_new_list_prim_f_32_strict(
    int len,
  ) {
    return _cst_new_list_prim_f_32_strict(len);
  }

  late final _cst_new_list_prim_f_32_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_f_32_strict> Function(ffi.Int32)
        >
      >('frbgen_moodiary_rust_cst_new_list_prim_f_32_strict');
  late final _cst_new_list_prim_f_32_strict = _cst_new_list_prim_f_32_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_f_32_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_i_32_loose> cst_new_list_prim_i_32_loose(
    int len,
  ) {
    return _cst_new_list_prim_i_32_loose(len);
  }

  late final _cst_new_list_prim_i_32_loosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_i_32_loose> Function(ffi.Int32)
        >
      >('frbgen_moodiary_rust_cst_new_list_prim_i_32_loose');
  late final _cst_new_list_prim_i_32_loose = _cst_new_list_prim_i_32_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_i_32_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_i_32_strict> cst_new_list_prim_i_32_strict(
    int len,
  ) {
    return _cst_new_list_prim_i_32_strict(len);
  }

  late final _cst_new_list_prim_i_32_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_i_32_strict> Function(ffi.Int32)
        >
      >('frbgen_moodiary_rust_cst_new_list_prim_i_32_strict');
  late final _cst_new_list_prim_i_32_strict = _cst_new_list_prim_i_32_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_i_32_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(len);
  }

  late final _cst_new_list_prim_u_8_loosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(ffi.Int32)
        >
      >('frbgen_moodiary_rust_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose = _cst_new_list_prim_u_8_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_moodiary_rust_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_record_string_f_32> cst_new_list_record_string_f_32(
    int len,
  ) {
    return _cst_new_list_record_string_f_32(len);
  }

  late final _cst_new_list_record_string_f_32Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_record_string_f_32> Function(ffi.Int32)
        >
      >('frbgen_moodiary_rust_cst_new_list_record_string_f_32');
  late final _cst_new_list_record_string_f_32 =
      _cst_new_list_record_string_f_32Ptr
          .asFunction<
            ffi.Pointer<wire_cst_list_record_string_f_32> Function(int)
          >();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_moodiary_rust_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReaderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_moodiary_rust_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReaderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZipPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_moodiary_rust_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZipPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_moodiary_rust_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReaderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_moodiary_rust_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReader =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFontReaderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZipPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_moodiary_rust_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZip =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZipPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  WireSyncRust2DartDco wire__crate__api__cancel__CancelToken_cancel(int that) {
    return _wire__crate__api__cancel__CancelToken_cancel(that);
  }

  late final _wire__crate__api__cancel__CancelToken_cancelPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_moodiary_rust_wire__crate__api__cancel__CancelToken_cancel',
      );
  late final _wire__crate__api__cancel__CancelToken_cancel =
      _wire__crate__api__cancel__CancelToken_cancelPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__cancel__CancelToken_is_cancelled(
    int that,
  ) {
    return _wire__crate__api__cancel__CancelToken_is_cancelled(that);
  }

  late final _wire__crate__api__cancel__CancelToken_is_cancelledPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_moodiary_rust_wire__crate__api__cancel__CancelToken_is_cancelled',
      );
  late final _wire__crate__api__cancel__CancelToken_is_cancelled =
      _wire__crate__api__cancel__CancelToken_is_cancelledPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__cancel__CancelToken_new() {
    return _wire__crate__api__cancel__CancelToken_new();
  }

  late final _wire__crate__api__cancel__CancelToken_newPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_moodiary_rust_wire__crate__api__cancel__CancelToken_new',
      );
  late final _wire__crate__api__cancel__CancelToken_new =
      _wire__crate__api__cancel__CancelToken_newPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__font__FontReader_get_font_name_from_ttf(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> ttf_file_path,
  ) {
    return _wire__crate__api__font__FontReader_get_font_name_from_ttf(
      port_,
      ttf_file_path,
    );
  }

  late final _wire__crate__api__font__FontReader_get_font_name_from_ttfPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_moodiary_rust_wire__crate__api__font__FontReader_get_font_name_from_ttf',
      );
  late final _wire__crate__api__font__FontReader_get_font_name_from_ttf =
      _wire__crate__api__font__FontReader_get_font_name_from_ttfPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__font__FontReader_get_wght_axis_from_vf_font(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> ttf_file_path,
  ) {
    return _wire__crate__api__font__FontReader_get_wght_axis_from_vf_font(
      port_,
      ttf_file_path,
    );
  }

  late final _wire__crate__api__font__FontReader_get_wght_axis_from_vf_fontPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_moodiary_rust_wire__crate__api__font__FontReader_get_wght_axis_from_vf_font',
      );
  late final _wire__crate__api__font__FontReader_get_wght_axis_from_vf_font =
      _wire__crate__api__font__FontReader_get_wght_axis_from_vf_fontPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__graph_layout__layout_graph_stream(
    int port_,
    int node_count,
    ffi.Pointer<wire_cst_list_prim_i_32_loose> edges,
    ffi.Pointer<wire_cst_list_prim_f_32_loose> initial_positions,
    ffi.Pointer<wire_cst_graph_layout_params> params,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> sink,
  ) {
    return _wire__crate__api__graph_layout__layout_graph_stream(
      port_,
      node_count,
      edges,
      initial_positions,
      params,
      sink,
    );
  }

  late final _wire__crate__api__graph_layout__layout_graph_streamPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Uint32,
            ffi.Pointer<wire_cst_list_prim_i_32_loose>,
            ffi.Pointer<wire_cst_list_prim_f_32_loose>,
            ffi.Pointer<wire_cst_graph_layout_params>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_moodiary_rust_wire__crate__api__graph_layout__layout_graph_stream',
      );
  late final _wire__crate__api__graph_layout__layout_graph_stream =
      _wire__crate__api__graph_layout__layout_graph_streamPtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_i_32_loose>,
              ffi.Pointer<wire_cst_list_prim_f_32_loose>,
              ffi.Pointer<wire_cst_graph_layout_params>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__zip__Zip_add_bytes(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> zip_path,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> data,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> password,
  ) {
    return _wire__crate__api__zip__Zip_add_bytes(
      port_,
      that,
      zip_path,
      data,
      password,
    );
  }

  late final _wire__crate__api__zip__Zip_add_bytesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_moodiary_rust_wire__crate__api__zip__Zip_add_bytes');
  late final _wire__crate__api__zip__Zip_add_bytes =
      _wire__crate__api__zip__Zip_add_bytesPtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__zip__Zip_add_file(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_path,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> zip_path,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> password,
    ffi.Pointer<ffi.Bool> stored,
  ) {
    return _wire__crate__api__zip__Zip_add_file(
      port_,
      that,
      file_path,
      zip_path,
      password,
      stored,
    );
  }

  late final _wire__crate__api__zip__Zip_add_filePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<ffi.Bool>,
          )
        >
      >('frbgen_moodiary_rust_wire__crate__api__zip__Zip_add_file');
  late final _wire__crate__api__zip__Zip_add_file =
      _wire__crate__api__zip__Zip_add_filePtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<ffi.Bool>,
            )
          >();

  void wire__crate__api__zip__Zip_extract(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> zip_path,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> dest_dir,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> password,
    int cancel,
  ) {
    return _wire__crate__api__zip__Zip_extract(
      port_,
      zip_path,
      dest_dir,
      password,
      cancel,
    );
  }

  late final _wire__crate__api__zip__Zip_extractPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.UintPtr,
          )
        >
      >('frbgen_moodiary_rust_wire__crate__api__zip__Zip_extract');
  late final _wire__crate__api__zip__Zip_extract =
      _wire__crate__api__zip__Zip_extractPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
            )
          >();

  void wire__crate__api__zip__Zip_finish(int port_, int that) {
    return _wire__crate__api__zip__Zip_finish(port_, that);
  }

  late final _wire__crate__api__zip__Zip_finishPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_moodiary_rust_wire__crate__api__zip__Zip_finish',
      );
  late final _wire__crate__api__zip__Zip_finish =
      _wire__crate__api__zip__Zip_finishPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__zip__Zip_new(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_path,
  ) {
    return _wire__crate__api__zip__Zip_new(port_, file_path);
  }

  late final _wire__crate__api__zip__Zip_newPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_moodiary_rust_wire__crate__api__zip__Zip_new');
  late final _wire__crate__api__zip__Zip_new =
      _wire__crate__api__zip__Zip_newPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;
typedef DartPostCObjectFnTypeFunction = ffi.Bool Function(
  DartPort port_id,
  ffi.Pointer<ffi.Void> message,
);
typedef DartDartPostCObjectFnTypeFunction = bool Function(
  DartDartPort port_id,
  ffi.Pointer<ffi.Void> message,
);

final class wire_cst_graph_layout_params extends ffi.Struct {
  @ffi.Uint32()
  external int iterations;

  @ffi.Float()
  external double theta;

  @ffi.Float()
  external double repulsion;

  @ffi.Float()
  external double spring_length;

  @ffi.Float()
  external double spring_strength;

  @ffi.Float()
  external double gravity;

  @ffi.Float()
  external double collide_radius;

  @ffi.Float()
  external double velocity_decay;

  @ffi.Uint32()
  external int emit_every;

  @ffi.Uint32()
  external int frame_delay_ms;

  @ffi.Float()
  external double initial_alpha;

  @ffi.Float()
  external double min_step;

  @ffi.Uint32()
  external int pinned_count;

  @ffi.Bool()
  external bool normalize_scale;

  static ffi.Pointer<wire_cst_graph_layout_params> $allocate(
    ffi.Allocator $allocator, {
    required int iterations,
    required double theta,
    required double repulsion,
    required double spring_length,
    required double spring_strength,
    required double gravity,
    required double collide_radius,
    required double velocity_decay,
    required int emit_every,
    required int frame_delay_ms,
    required double initial_alpha,
    required double min_step,
    required int pinned_count,
    required bool normalize_scale,
  }) => $allocator<wire_cst_graph_layout_params>()
    ..ref.iterations = iterations
    ..ref.theta = theta
    ..ref.repulsion = repulsion
    ..ref.spring_length = spring_length
    ..ref.spring_strength = spring_strength
    ..ref.gravity = gravity
    ..ref.collide_radius = collide_radius
    ..ref.velocity_decay = velocity_decay
    ..ref.emit_every = emit_every
    ..ref.frame_delay_ms = frame_delay_ms
    ..ref.initial_alpha = initial_alpha
    ..ref.min_step = min_step
    ..ref.pinned_count = pinned_count
    ..ref.normalize_scale = normalize_scale;
}

final class wire_cst_list_prim_f_32_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Float> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_prim_f_32_loose> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Float> ptr,
    required int len,
  }) => $allocator<wire_cst_list_prim_f_32_loose>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_prim_f_32_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Float> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_prim_f_32_strict> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Float> ptr,
    required int len,
  }) => $allocator<wire_cst_list_prim_f_32_strict>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_prim_i_32_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Int32> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_prim_i_32_loose> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Int32> ptr,
    required int len,
  }) => $allocator<wire_cst_list_prim_i_32_loose>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_prim_i_32_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Int32> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_prim_i_32_strict> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Int32> ptr,
    required int len,
  }) => $allocator<wire_cst_list_prim_i_32_strict>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_prim_u_8_loose> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Uint8> ptr,
    required int len,
  }) => $allocator<wire_cst_list_prim_u_8_loose>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_prim_u_8_strict> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Uint8> ptr,
    required int len,
  }) => $allocator<wire_cst_list_prim_u_8_strict>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_record_string_f_32 extends ffi.Struct {
  external ffi.Pointer<wire_cst_record_string_f_32> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_record_string_f_32> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_record_string_f_32> ptr,
    required int len,
  }) => $allocator<wire_cst_list_record_string_f_32>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_record_string_f_32 extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field0;

  @ffi.Float()
  external double field1;

  static ffi.Pointer<wire_cst_record_string_f_32> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> field0,
    required double field1,
  }) => $allocator<wire_cst_record_string_f_32>()
    ..ref.field0 = field0
    ..ref.field1 = field1;
}
