// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/cancel.dart';
import 'api/docx.dart';
import 'api/ir.dart';
import 'api/pdf.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class FastPressLibApiImplPlatform
    extends BaseApiImpl<FastPressLibWire> {
  FastPressLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CancelTokenPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_DocxBuilderPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilderPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PdfBuilderPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilderPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  CancelToken
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    dynamic raw,
  );

  @protected
  DocxBuilder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
    dynamic raw,
  );

  @protected
  PdfBuilder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
    dynamic raw,
  );

  @protected
  DocxBuilder
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
    dynamic raw,
  );

  @protected
  PdfBuilder
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
    dynamic raw,
  );

  @protected
  CancelToken
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    dynamic raw,
  );

  @protected
  CancelToken
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    dynamic raw,
  );

  @protected
  DocxBuilder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
    dynamic raw,
  );

  @protected
  PdfBuilder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  DocxStyle dco_decode_box_autoadd_docx_style(dynamic raw);

  @protected
  IrDoc dco_decode_box_autoadd_ir_doc(dynamic raw);

  @protected
  PdfStyle dco_decode_box_autoadd_pdf_style(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  DocxStyle dco_decode_docx_style(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  IrBlock dco_decode_ir_block(dynamic raw);

  @protected
  IrCell dco_decode_ir_cell(dynamic raw);

  @protected
  IrDoc dco_decode_ir_doc(dynamic raw);

  @protected
  IrListItem dco_decode_ir_list_item(dynamic raw);

  @protected
  IrRow dco_decode_ir_row(dynamic raw);

  @protected
  IrSpan dco_decode_ir_span(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<IrBlock> dco_decode_list_ir_block(dynamic raw);

  @protected
  List<IrCell> dco_decode_list_ir_cell(dynamic raw);

  @protected
  List<IrDoc> dco_decode_list_ir_doc(dynamic raw);

  @protected
  List<IrListItem> dco_decode_list_ir_list_item(dynamic raw);

  @protected
  List<IrRow> dco_decode_list_ir_row(dynamic raw);

  @protected
  List<IrSpan> dco_decode_list_ir_span(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PdfStyle dco_decode_pdf_style(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  CancelToken
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    SseDeserializer deserializer,
  );

  @protected
  DocxBuilder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
    SseDeserializer deserializer,
  );

  @protected
  PdfBuilder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
    SseDeserializer deserializer,
  );

  @protected
  DocxBuilder
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
    SseDeserializer deserializer,
  );

  @protected
  PdfBuilder
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
    SseDeserializer deserializer,
  );

  @protected
  CancelToken
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    SseDeserializer deserializer,
  );

  @protected
  CancelToken
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    SseDeserializer deserializer,
  );

  @protected
  DocxBuilder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
    SseDeserializer deserializer,
  );

  @protected
  PdfBuilder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DocxStyle sse_decode_box_autoadd_docx_style(SseDeserializer deserializer);

  @protected
  IrDoc sse_decode_box_autoadd_ir_doc(SseDeserializer deserializer);

  @protected
  PdfStyle sse_decode_box_autoadd_pdf_style(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  DocxStyle sse_decode_docx_style(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  IrBlock sse_decode_ir_block(SseDeserializer deserializer);

  @protected
  IrCell sse_decode_ir_cell(SseDeserializer deserializer);

  @protected
  IrDoc sse_decode_ir_doc(SseDeserializer deserializer);

  @protected
  IrListItem sse_decode_ir_list_item(SseDeserializer deserializer);

  @protected
  IrRow sse_decode_ir_row(SseDeserializer deserializer);

  @protected
  IrSpan sse_decode_ir_span(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<IrBlock> sse_decode_list_ir_block(SseDeserializer deserializer);

  @protected
  List<IrCell> sse_decode_list_ir_cell(SseDeserializer deserializer);

  @protected
  List<IrDoc> sse_decode_list_ir_doc(SseDeserializer deserializer);

  @protected
  List<IrListItem> sse_decode_list_ir_list_item(SseDeserializer deserializer);

  @protected
  List<IrRow> sse_decode_list_ir_row(SseDeserializer deserializer);

  @protected
  List<IrSpan> sse_decode_list_ir_span(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PdfStyle sse_decode_pdf_style(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
    AnyhowException raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.Bool> cst_encode_box_autoadd_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_bool(cst_encode_bool(raw));
  }

  @protected
  ffi.Pointer<wire_cst_docx_style> cst_encode_box_autoadd_docx_style(
    DocxStyle raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_docx_style();
    cst_api_fill_to_wire_docx_style(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_ir_doc> cst_encode_box_autoadd_ir_doc(IrDoc raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_ir_doc();
    cst_api_fill_to_wire_ir_doc(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_pdf_style> cst_encode_box_autoadd_pdf_style(
    PdfStyle raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_pdf_style();
    cst_api_fill_to_wire_pdf_style(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Uint32> cst_encode_box_autoadd_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_u_32(cst_encode_u_32(raw));
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_ir_block> cst_encode_list_ir_block(
    List<IrBlock> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_ir_block(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_ir_block(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_ir_cell> cst_encode_list_ir_cell(List<IrCell> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_ir_cell(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_ir_cell(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_ir_doc> cst_encode_list_ir_doc(List<IrDoc> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_ir_doc(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_ir_doc(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_ir_list_item> cst_encode_list_ir_list_item(
    List<IrListItem> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_ir_list_item(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_ir_list_item(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_ir_row> cst_encode_list_ir_row(List<IrRow> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_ir_row(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_ir_row(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_ir_span> cst_encode_list_ir_span(List<IrSpan> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_ir_span(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_ir_span(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Bool> cst_encode_opt_box_autoadd_bool(bool? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_bool(raw);
  }

  @protected
  ffi.Pointer<ffi.Uint32> cst_encode_opt_box_autoadd_u_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_u_32(raw);
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_docx_style(
    DocxStyle apiObj,
    ffi.Pointer<wire_cst_docx_style> wireObj,
  ) {
    cst_api_fill_to_wire_docx_style(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_ir_doc(
    IrDoc apiObj,
    ffi.Pointer<wire_cst_ir_doc> wireObj,
  ) {
    cst_api_fill_to_wire_ir_doc(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_pdf_style(
    PdfStyle apiObj,
    ffi.Pointer<wire_cst_pdf_style> wireObj,
  ) {
    cst_api_fill_to_wire_pdf_style(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_docx_style(
    DocxStyle apiObj,
    wire_cst_docx_style wireObj,
  ) {
    wireObj.east_asia_font = cst_encode_String(apiObj.eastAsiaFont);
    wireObj.ascii_font = cst_encode_String(apiObj.asciiFont);
    wireObj.font_size_pt = cst_encode_f_64(apiObj.fontSizePt);
    wireObj.line_spacing = cst_encode_f_64(apiObj.lineSpacing);
    wireObj.first_line_indent = cst_encode_bool(apiObj.firstLineIndent);
    wireObj.page_width = cst_encode_u_32(apiObj.pageWidth);
    wireObj.page_height = cst_encode_u_32(apiObj.pageHeight);
    wireObj.page_margin = cst_encode_u_32(apiObj.pageMargin);
    wireObj.include_title = cst_encode_bool(apiObj.includeTitle);
    wireObj.include_meta = cst_encode_bool(apiObj.includeMeta);
    wireObj.page_break_between = cst_encode_bool(apiObj.pageBreakBetween);
    wireObj.video_label = cst_encode_String(apiObj.videoLabel);
    wireObj.audio_label = cst_encode_String(apiObj.audioLabel);
  }

  @protected
  void cst_api_fill_to_wire_ir_block(
    IrBlock apiObj,
    wire_cst_ir_block wireObj,
  ) {
    if (apiObj is IrBlock_Paragraph) {
      var pre_spans = cst_encode_list_ir_span(apiObj.spans);
      wireObj.tag = 0;
      wireObj.kind.Paragraph.spans = pre_spans;
      return;
    }
    if (apiObj is IrBlock_Heading) {
      var pre_level = cst_encode_u_32(apiObj.level);
      var pre_spans = cst_encode_list_ir_span(apiObj.spans);
      wireObj.tag = 1;
      wireObj.kind.Heading.level = pre_level;
      wireObj.kind.Heading.spans = pre_spans;
      return;
    }
    if (apiObj is IrBlock_List) {
      var pre_ordered = cst_encode_bool(apiObj.ordered);
      var pre_start = cst_encode_u_32(apiObj.start);
      var pre_items = cst_encode_list_ir_list_item(apiObj.items);
      wireObj.tag = 2;
      wireObj.kind.List.ordered = pre_ordered;
      wireObj.kind.List.start = pre_start;
      wireObj.kind.List.items = pre_items;
      return;
    }
    if (apiObj is IrBlock_Quote) {
      var pre_children = cst_encode_list_ir_block(apiObj.children);
      wireObj.tag = 3;
      wireObj.kind.Quote.children = pre_children;
      return;
    }
    if (apiObj is IrBlock_Code) {
      var pre_language = cst_encode_opt_String(apiObj.language);
      var pre_text = cst_encode_String(apiObj.text);
      wireObj.tag = 4;
      wireObj.kind.Code.language = pre_language;
      wireObj.kind.Code.text = pre_text;
      return;
    }
    if (apiObj is IrBlock_Divider) {
      wireObj.tag = 5;
      return;
    }
    if (apiObj is IrBlock_Image) {
      var pre_path = cst_encode_String(apiObj.path);
      var pre_alt = cst_encode_opt_String(apiObj.alt);
      var pre_width_percent = cst_encode_opt_box_autoadd_u_32(
        apiObj.widthPercent,
      );
      var pre_is_external = cst_encode_bool(apiObj.isExternal);
      wireObj.tag = 6;
      wireObj.kind.Image.path = pre_path;
      wireObj.kind.Image.alt = pre_alt;
      wireObj.kind.Image.width_percent = pre_width_percent;
      wireObj.kind.Image.is_external = pre_is_external;
      return;
    }
    if (apiObj is IrBlock_Media) {
      var pre_kind = cst_encode_String(apiObj.kind);
      var pre_filename = cst_encode_String(apiObj.filename);
      var pre_path = cst_encode_String(apiObj.path);
      var pre_cover_path = cst_encode_opt_String(apiObj.coverPath);
      wireObj.tag = 7;
      wireObj.kind.Media.kind = pre_kind;
      wireObj.kind.Media.filename = pre_filename;
      wireObj.kind.Media.path = pre_path;
      wireObj.kind.Media.cover_path = pre_cover_path;
      return;
    }
    if (apiObj is IrBlock_Table) {
      var pre_rows = cst_encode_list_ir_row(apiObj.rows);
      wireObj.tag = 8;
      wireObj.kind.Table.rows = pre_rows;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_ir_cell(IrCell apiObj, wire_cst_ir_cell wireObj) {
    wireObj.children = cst_encode_list_ir_block(apiObj.children);
    wireObj.colspan = cst_encode_u_32(apiObj.colspan);
    wireObj.rowspan = cst_encode_u_32(apiObj.rowspan);
    wireObj.align = cst_encode_opt_String(apiObj.align);
    wireObj.header = cst_encode_bool(apiObj.header);
  }

  @protected
  void cst_api_fill_to_wire_ir_doc(IrDoc apiObj, wire_cst_ir_doc wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.title = cst_encode_String(apiObj.title);
    wireObj.time = cst_encode_String(apiObj.time);
    wireObj.weather = cst_encode_list_String(apiObj.weather);
    wireObj.position = cst_encode_list_String(apiObj.position);
    wireObj.tags = cst_encode_list_String(apiObj.tags);
    wireObj.category_name = cst_encode_opt_String(apiObj.categoryName);
    wireObj.blocks = cst_encode_list_ir_block(apiObj.blocks);
  }

  @protected
  void cst_api_fill_to_wire_ir_list_item(
    IrListItem apiObj,
    wire_cst_ir_list_item wireObj,
  ) {
    wireObj.children = cst_encode_list_ir_block(apiObj.children);
    wireObj.checked = cst_encode_opt_box_autoadd_bool(apiObj.checked);
  }

  @protected
  void cst_api_fill_to_wire_ir_row(IrRow apiObj, wire_cst_ir_row wireObj) {
    wireObj.cells = cst_encode_list_ir_cell(apiObj.cells);
  }

  @protected
  void cst_api_fill_to_wire_ir_span(IrSpan apiObj, wire_cst_ir_span wireObj) {
    wireObj.text = cst_encode_String(apiObj.text);
    wireObj.bold = cst_encode_bool(apiObj.bold);
    wireObj.italic = cst_encode_bool(apiObj.italic);
    wireObj.strike = cst_encode_bool(apiObj.strike);
    wireObj.underline = cst_encode_bool(apiObj.underline);
    wireObj.code = cst_encode_bool(apiObj.code);
    wireObj.href = cst_encode_opt_String(apiObj.href);
    wireObj.diary_link_id = cst_encode_opt_String(apiObj.diaryLinkId);
  }

  @protected
  void cst_api_fill_to_wire_pdf_style(
    PdfStyle apiObj,
    wire_cst_pdf_style wireObj,
  ) {
    wireObj.font_path = cst_encode_String(apiObj.fontPath);
    wireObj.font_family = cst_encode_String(apiObj.fontFamily);
    wireObj.font_size_pt = cst_encode_f_64(apiObj.fontSizePt);
    wireObj.line_spacing_em = cst_encode_f_64(apiObj.lineSpacingEm);
    wireObj.first_line_indent = cst_encode_bool(apiObj.firstLineIndent);
    wireObj.page_width_mm = cst_encode_f_64(apiObj.pageWidthMm);
    wireObj.page_height_mm = cst_encode_f_64(apiObj.pageHeightMm);
    wireObj.page_margin_mm = cst_encode_f_64(apiObj.pageMarginMm);
    wireObj.include_title = cst_encode_bool(apiObj.includeTitle);
    wireObj.include_meta = cst_encode_bool(apiObj.includeMeta);
    wireObj.video_label = cst_encode_String(apiObj.videoLabel);
    wireObj.audio_label = cst_encode_String(apiObj.audioLabel);
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    CancelToken raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
    DocxBuilder raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
    PdfBuilder raw,
  );

  @protected
  int
  cst_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
    DocxBuilder raw,
  );

  @protected
  int
  cst_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
    PdfBuilder raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    CancelToken raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    CancelToken raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
    DocxBuilder raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
    PdfBuilder raw,
  );

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    CancelToken self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
    DocxBuilder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
    PdfBuilder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
    DocxBuilder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
    PdfBuilder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    CancelToken self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    CancelToken self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
    DocxBuilder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
    PdfBuilder self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_docx_style(
    DocxStyle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ir_doc(IrDoc self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_pdf_style(
    PdfStyle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_docx_style(DocxStyle self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_ir_block(IrBlock self, SseSerializer serializer);

  @protected
  void sse_encode_ir_cell(IrCell self, SseSerializer serializer);

  @protected
  void sse_encode_ir_doc(IrDoc self, SseSerializer serializer);

  @protected
  void sse_encode_ir_list_item(IrListItem self, SseSerializer serializer);

  @protected
  void sse_encode_ir_row(IrRow self, SseSerializer serializer);

  @protected
  void sse_encode_ir_span(IrSpan self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ir_block(List<IrBlock> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ir_cell(List<IrCell> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ir_doc(List<IrDoc> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ir_list_item(
    List<IrListItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ir_row(List<IrRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ir_span(List<IrSpan> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_pdf_style(PdfStyle self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package

/// generated by flutter_rust_bridge
class FastPressLibWire implements BaseWire {
  factory FastPressLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      FastPressLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FastPressLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FastPressLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<ffi.Bool> cst_new_box_autoadd_bool(bool value) {
    return _cst_new_box_autoadd_bool(value);
  }

  late final _cst_new_box_autoadd_boolPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Bool> Function(ffi.Bool)>>(
        'frbgen_fast_press_cst_new_box_autoadd_bool',
      );
  late final _cst_new_box_autoadd_bool = _cst_new_box_autoadd_boolPtr
      .asFunction<ffi.Pointer<ffi.Bool> Function(bool)>();

  ffi.Pointer<wire_cst_docx_style> cst_new_box_autoadd_docx_style() {
    return _cst_new_box_autoadd_docx_style();
  }

  late final _cst_new_box_autoadd_docx_stylePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_docx_style> Function()>>(
        'frbgen_fast_press_cst_new_box_autoadd_docx_style',
      );
  late final _cst_new_box_autoadd_docx_style =
      _cst_new_box_autoadd_docx_stylePtr
          .asFunction<ffi.Pointer<wire_cst_docx_style> Function()>();

  ffi.Pointer<wire_cst_ir_doc> cst_new_box_autoadd_ir_doc() {
    return _cst_new_box_autoadd_ir_doc();
  }

  late final _cst_new_box_autoadd_ir_docPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_ir_doc> Function()>>(
        'frbgen_fast_press_cst_new_box_autoadd_ir_doc',
      );
  late final _cst_new_box_autoadd_ir_doc = _cst_new_box_autoadd_ir_docPtr
      .asFunction<ffi.Pointer<wire_cst_ir_doc> Function()>();

  ffi.Pointer<wire_cst_pdf_style> cst_new_box_autoadd_pdf_style() {
    return _cst_new_box_autoadd_pdf_style();
  }

  late final _cst_new_box_autoadd_pdf_stylePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_pdf_style> Function()>>(
        'frbgen_fast_press_cst_new_box_autoadd_pdf_style',
      );
  late final _cst_new_box_autoadd_pdf_style = _cst_new_box_autoadd_pdf_stylePtr
      .asFunction<ffi.Pointer<wire_cst_pdf_style> Function()>();

  ffi.Pointer<ffi.Uint32> cst_new_box_autoadd_u_32(int value) {
    return _cst_new_box_autoadd_u_32(value);
  }

  late final _cst_new_box_autoadd_u_32Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Uint32> Function(ffi.Uint32)>>(
        'frbgen_fast_press_cst_new_box_autoadd_u_32',
      );
  late final _cst_new_box_autoadd_u_32 = _cst_new_box_autoadd_u_32Ptr
      .asFunction<ffi.Pointer<ffi.Uint32> Function(int)>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(int len) {
    return _cst_new_list_String(len);
  }

  late final _cst_new_list_StringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(ffi.Int32)
        >
      >('frbgen_fast_press_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_ir_block> cst_new_list_ir_block(int len) {
    return _cst_new_list_ir_block(len);
  }

  late final _cst_new_list_ir_blockPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_ir_block> Function(ffi.Int32)
        >
      >('frbgen_fast_press_cst_new_list_ir_block');
  late final _cst_new_list_ir_block = _cst_new_list_ir_blockPtr
      .asFunction<ffi.Pointer<wire_cst_list_ir_block> Function(int)>();

  ffi.Pointer<wire_cst_list_ir_cell> cst_new_list_ir_cell(int len) {
    return _cst_new_list_ir_cell(len);
  }

  late final _cst_new_list_ir_cellPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_ir_cell> Function(ffi.Int32)
        >
      >('frbgen_fast_press_cst_new_list_ir_cell');
  late final _cst_new_list_ir_cell = _cst_new_list_ir_cellPtr
      .asFunction<ffi.Pointer<wire_cst_list_ir_cell> Function(int)>();

  ffi.Pointer<wire_cst_list_ir_doc> cst_new_list_ir_doc(int len) {
    return _cst_new_list_ir_doc(len);
  }

  late final _cst_new_list_ir_docPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_ir_doc> Function(ffi.Int32)
        >
      >('frbgen_fast_press_cst_new_list_ir_doc');
  late final _cst_new_list_ir_doc = _cst_new_list_ir_docPtr
      .asFunction<ffi.Pointer<wire_cst_list_ir_doc> Function(int)>();

  ffi.Pointer<wire_cst_list_ir_list_item> cst_new_list_ir_list_item(int len) {
    return _cst_new_list_ir_list_item(len);
  }

  late final _cst_new_list_ir_list_itemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_ir_list_item> Function(ffi.Int32)
        >
      >('frbgen_fast_press_cst_new_list_ir_list_item');
  late final _cst_new_list_ir_list_item = _cst_new_list_ir_list_itemPtr
      .asFunction<ffi.Pointer<wire_cst_list_ir_list_item> Function(int)>();

  ffi.Pointer<wire_cst_list_ir_row> cst_new_list_ir_row(int len) {
    return _cst_new_list_ir_row(len);
  }

  late final _cst_new_list_ir_rowPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_ir_row> Function(ffi.Int32)
        >
      >('frbgen_fast_press_cst_new_list_ir_row');
  late final _cst_new_list_ir_row = _cst_new_list_ir_rowPtr
      .asFunction<ffi.Pointer<wire_cst_list_ir_row> Function(int)>();

  ffi.Pointer<wire_cst_list_ir_span> cst_new_list_ir_span(int len) {
    return _cst_new_list_ir_span(len);
  }

  late final _cst_new_list_ir_spanPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_ir_span> Function(ffi.Int32)
        >
      >('frbgen_fast_press_cst_new_list_ir_span');
  late final _cst_new_list_ir_span = _cst_new_list_ir_spanPtr
      .asFunction<ffi.Pointer<wire_cst_list_ir_span> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_fast_press_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_fast_press_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_fast_press_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_fast_press_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_fast_press_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_fast_press_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilder =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocxBuilderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_fast_press_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilder =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPdfBuilderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  WireSyncRust2DartDco wire__crate__api__cancel__CancelToken_cancel(int that) {
    return _wire__crate__api__cancel__CancelToken_cancel(that);
  }

  late final _wire__crate__api__cancel__CancelToken_cancelPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_fast_press_wire__crate__api__cancel__CancelToken_cancel',
      );
  late final _wire__crate__api__cancel__CancelToken_cancel =
      _wire__crate__api__cancel__CancelToken_cancelPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__cancel__CancelToken_is_cancelled(
    int that,
  ) {
    return _wire__crate__api__cancel__CancelToken_is_cancelled(that);
  }

  late final _wire__crate__api__cancel__CancelToken_is_cancelledPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_fast_press_wire__crate__api__cancel__CancelToken_is_cancelled',
      );
  late final _wire__crate__api__cancel__CancelToken_is_cancelled =
      _wire__crate__api__cancel__CancelToken_is_cancelledPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__cancel__CancelToken_new() {
    return _wire__crate__api__cancel__CancelToken_new();
  }

  late final _wire__crate__api__cancel__CancelToken_newPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_fast_press_wire__crate__api__cancel__CancelToken_new',
      );
  late final _wire__crate__api__cancel__CancelToken_new =
      _wire__crate__api__cancel__CancelToken_newPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__docx__DocxBuilder_add(
    int port_,
    int that,
    ffi.Pointer<wire_cst_ir_doc> doc,
  ) {
    return _wire__crate__api__docx__DocxBuilder_add(port_, that, doc);
  }

  late final _wire__crate__api__docx__DocxBuilder_addPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_ir_doc>,
          )
        >
      >('frbgen_fast_press_wire__crate__api__docx__DocxBuilder_add');
  late final _wire__crate__api__docx__DocxBuilder_add =
      _wire__crate__api__docx__DocxBuilder_addPtr
          .asFunction<void Function(int, int, ffi.Pointer<wire_cst_ir_doc>)>();

  void wire__crate__api__docx__DocxBuilder_finish(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> out_path,
    int cancel,
  ) {
    return _wire__crate__api__docx__DocxBuilder_finish(
      port_,
      that,
      out_path,
      cancel,
    );
  }

  late final _wire__crate__api__docx__DocxBuilder_finishPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.UintPtr,
          )
        >
      >('frbgen_fast_press_wire__crate__api__docx__DocxBuilder_finish');
  late final _wire__crate__api__docx__DocxBuilder_finish =
      _wire__crate__api__docx__DocxBuilder_finishPtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
            )
          >();

  void wire__crate__api__docx__DocxBuilder_new(
    int port_,
    ffi.Pointer<wire_cst_docx_style> style,
  ) {
    return _wire__crate__api__docx__DocxBuilder_new(port_, style);
  }

  late final _wire__crate__api__docx__DocxBuilder_newPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_docx_style>)
        >
      >('frbgen_fast_press_wire__crate__api__docx__DocxBuilder_new');
  late final _wire__crate__api__docx__DocxBuilder_new =
      _wire__crate__api__docx__DocxBuilder_newPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_docx_style>)>();

  void wire__crate__api__docx__write_docx(
    int port_,
    ffi.Pointer<wire_cst_list_ir_doc> docs,
    ffi.Pointer<wire_cst_docx_style> style,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> out_path,
    int cancel,
  ) {
    return _wire__crate__api__docx__write_docx(
      port_,
      docs,
      style,
      out_path,
      cancel,
    );
  }

  late final _wire__crate__api__docx__write_docxPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_ir_doc>,
            ffi.Pointer<wire_cst_docx_style>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.UintPtr,
          )
        >
      >('frbgen_fast_press_wire__crate__api__docx__write_docx');
  late final _wire__crate__api__docx__write_docx =
      _wire__crate__api__docx__write_docxPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_ir_doc>,
              ffi.Pointer<wire_cst_docx_style>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
            )
          >();

  void wire__crate__api__pdf__PdfBuilder_add(
    int port_,
    int that,
    ffi.Pointer<wire_cst_ir_doc> doc,
  ) {
    return _wire__crate__api__pdf__PdfBuilder_add(port_, that, doc);
  }

  late final _wire__crate__api__pdf__PdfBuilder_addPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_ir_doc>,
          )
        >
      >('frbgen_fast_press_wire__crate__api__pdf__PdfBuilder_add');
  late final _wire__crate__api__pdf__PdfBuilder_add =
      _wire__crate__api__pdf__PdfBuilder_addPtr
          .asFunction<void Function(int, int, ffi.Pointer<wire_cst_ir_doc>)>();

  void wire__crate__api__pdf__PdfBuilder_finish(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> out_path,
    int cancel,
  ) {
    return _wire__crate__api__pdf__PdfBuilder_finish(
      port_,
      that,
      out_path,
      cancel,
    );
  }

  late final _wire__crate__api__pdf__PdfBuilder_finishPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.UintPtr,
          )
        >
      >('frbgen_fast_press_wire__crate__api__pdf__PdfBuilder_finish');
  late final _wire__crate__api__pdf__PdfBuilder_finish =
      _wire__crate__api__pdf__PdfBuilder_finishPtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
            )
          >();

  void wire__crate__api__pdf__PdfBuilder_new(
    int port_,
    ffi.Pointer<wire_cst_pdf_style> style,
  ) {
    return _wire__crate__api__pdf__PdfBuilder_new(port_, style);
  }

  late final _wire__crate__api__pdf__PdfBuilder_newPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_pdf_style>)
        >
      >('frbgen_fast_press_wire__crate__api__pdf__PdfBuilder_new');
  late final _wire__crate__api__pdf__PdfBuilder_new =
      _wire__crate__api__pdf__PdfBuilder_newPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_pdf_style>)>();

  void wire__crate__api__pdf__write_pdf(
    int port_,
    ffi.Pointer<wire_cst_list_ir_doc> docs,
    ffi.Pointer<wire_cst_pdf_style> style,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> out_path,
    int cancel,
  ) {
    return _wire__crate__api__pdf__write_pdf(
      port_,
      docs,
      style,
      out_path,
      cancel,
    );
  }

  late final _wire__crate__api__pdf__write_pdfPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_ir_doc>,
            ffi.Pointer<wire_cst_pdf_style>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.UintPtr,
          )
        >
      >('frbgen_fast_press_wire__crate__api__pdf__write_pdf');
  late final _wire__crate__api__pdf__write_pdf =
      _wire__crate__api__pdf__write_pdfPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_ir_doc>,
              ffi.Pointer<wire_cst_pdf_style>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
            )
          >();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;
typedef DartPostCObjectFnTypeFunction = ffi.Bool Function(
  DartPort port_id,
  ffi.Pointer<ffi.Void> message,
);
typedef DartDartPostCObjectFnTypeFunction = bool Function(
  DartDartPort port_id,
  ffi.Pointer<ffi.Void> message,
);

final class IrBlockKind extends ffi.Union {
  external wire_cst_IrBlock_Paragraph Paragraph;

  external wire_cst_IrBlock_Heading Heading;

  external wire_cst_IrBlock_List List;

  external wire_cst_IrBlock_Quote Quote;

  external wire_cst_IrBlock_Code Code;

  external wire_cst_IrBlock_Image Image;

  external wire_cst_IrBlock_Media Media;

  external wire_cst_IrBlock_Table Table;
}

final class wire_cst_IrBlock_Code extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> language;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> text;

  static ffi.Pointer<wire_cst_IrBlock_Code> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> language,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
  }) => $allocator<wire_cst_IrBlock_Code>()
    ..ref.language = language
    ..ref.text = text;
}

final class wire_cst_IrBlock_Heading extends ffi.Struct {
  @ffi.Uint32()
  external int level;

  external ffi.Pointer<wire_cst_list_ir_span> spans;

  static ffi.Pointer<wire_cst_IrBlock_Heading> $allocate(
    ffi.Allocator $allocator, {
    required int level,
    required ffi.Pointer<wire_cst_list_ir_span> spans,
  }) => $allocator<wire_cst_IrBlock_Heading>()
    ..ref.level = level
    ..ref.spans = spans;
}

final class wire_cst_IrBlock_Image extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> path;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> alt;

  external ffi.Pointer<ffi.Uint32> width_percent;

  @ffi.Bool()
  external bool is_external;

  static ffi.Pointer<wire_cst_IrBlock_Image> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> alt,
    required ffi.Pointer<ffi.Uint32> width_percent,
    required bool is_external,
  }) => $allocator<wire_cst_IrBlock_Image>()
    ..ref.path = path
    ..ref.alt = alt
    ..ref.width_percent = width_percent
    ..ref.is_external = is_external;
}

final class wire_cst_IrBlock_List extends ffi.Struct {
  @ffi.Bool()
  external bool ordered;

  @ffi.Uint32()
  external int start;

  external ffi.Pointer<wire_cst_list_ir_list_item> items;

  static ffi.Pointer<wire_cst_IrBlock_List> $allocate(
    ffi.Allocator $allocator, {
    required bool ordered,
    required int start,
    required ffi.Pointer<wire_cst_list_ir_list_item> items,
  }) => $allocator<wire_cst_IrBlock_List>()
    ..ref.ordered = ordered
    ..ref.start = start
    ..ref.items = items;
}

final class wire_cst_IrBlock_Media extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> kind;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> filename;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> path;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> cover_path;

  static ffi.Pointer<wire_cst_IrBlock_Media> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> kind,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> filename,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> cover_path,
  }) => $allocator<wire_cst_IrBlock_Media>()
    ..ref.kind = kind
    ..ref.filename = filename
    ..ref.path = path
    ..ref.cover_path = cover_path;
}

final class wire_cst_IrBlock_Paragraph extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_ir_span> spans;

  static ffi.Pointer<wire_cst_IrBlock_Paragraph> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_ir_span> spans,
  }) => $allocator<wire_cst_IrBlock_Paragraph>()..ref.spans = spans;
}

final class wire_cst_IrBlock_Quote extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_ir_block> children;

  static ffi.Pointer<wire_cst_IrBlock_Quote> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_ir_block> children,
  }) => $allocator<wire_cst_IrBlock_Quote>()..ref.children = children;
}

final class wire_cst_IrBlock_Table extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_ir_row> rows;

  static ffi.Pointer<wire_cst_IrBlock_Table> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_ir_row> rows,
  }) => $allocator<wire_cst_IrBlock_Table>()..ref.rows = rows;
}

final class wire_cst_docx_style extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> east_asia_font;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> ascii_font;

  @ffi.Double()
  external double font_size_pt;

  @ffi.Double()
  external double line_spacing;

  @ffi.Bool()
  external bool first_line_indent;

  @ffi.Uint32()
  external int page_width;

  @ffi.Uint32()
  external int page_height;

  @ffi.Uint32()
  external int page_margin;

  @ffi.Bool()
  external bool include_title;

  @ffi.Bool()
  external bool include_meta;

  @ffi.Bool()
  external bool page_break_between;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> video_label;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> audio_label;

  static ffi.Pointer<wire_cst_docx_style> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> east_asia_font,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> ascii_font,
    required double font_size_pt,
    required double line_spacing,
    required bool first_line_indent,
    required int page_width,
    required int page_height,
    required int page_margin,
    required bool include_title,
    required bool include_meta,
    required bool page_break_between,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> video_label,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> audio_label,
  }) => $allocator<wire_cst_docx_style>()
    ..ref.east_asia_font = east_asia_font
    ..ref.ascii_font = ascii_font
    ..ref.font_size_pt = font_size_pt
    ..ref.line_spacing = line_spacing
    ..ref.first_line_indent = first_line_indent
    ..ref.page_width = page_width
    ..ref.page_height = page_height
    ..ref.page_margin = page_margin
    ..ref.include_title = include_title
    ..ref.include_meta = include_meta
    ..ref.page_break_between = page_break_between
    ..ref.video_label = video_label
    ..ref.audio_label = audio_label;
}

final class wire_cst_ir_block extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external IrBlockKind kind;
}

final class wire_cst_ir_cell extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_ir_block> children;

  @ffi.Uint32()
  external int colspan;

  @ffi.Uint32()
  external int rowspan;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> align;

  @ffi.Bool()
  external bool header;

  static ffi.Pointer<wire_cst_ir_cell> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_ir_block> children,
    required int colspan,
    required int rowspan,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> align,
    required bool header,
  }) => $allocator<wire_cst_ir_cell>()
    ..ref.children = children
    ..ref.colspan = colspan
    ..ref.rowspan = rowspan
    ..ref.align = align
    ..ref.header = header;
}

final class wire_cst_ir_doc extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> time;

  external ffi.Pointer<wire_cst_list_String> weather;

  external ffi.Pointer<wire_cst_list_String> position;

  external ffi.Pointer<wire_cst_list_String> tags;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> category_name;

  external ffi.Pointer<wire_cst_list_ir_block> blocks;

  static ffi.Pointer<wire_cst_ir_doc> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> time,
    required ffi.Pointer<wire_cst_list_String> weather,
    required ffi.Pointer<wire_cst_list_String> position,
    required ffi.Pointer<wire_cst_list_String> tags,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> category_name,
    required ffi.Pointer<wire_cst_list_ir_block> blocks,
  }) => $allocator<wire_cst_ir_doc>()
    ..ref.id = id
    ..ref.title = title
    ..ref.time = time
    ..ref.weather = weather
    ..ref.position = position
    ..ref.tags = tags
    ..ref.category_name = category_name
    ..ref.blocks = blocks;
}

final class wire_cst_ir_list_item extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_ir_block> children;

  external ffi.Pointer<ffi.Bool> checked;

  static ffi.Pointer<wire_cst_ir_list_item> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_ir_block> children,
    required ffi.Pointer<ffi.Bool> checked,
  }) => $allocator<wire_cst_ir_list_item>()
    ..ref.children = children
    ..ref.checked = checked;
}

final class wire_cst_ir_row extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_ir_cell> cells;

  static ffi.Pointer<wire_cst_ir_row> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_ir_cell> cells,
  }) => $allocator<wire_cst_ir_row>()..ref.cells = cells;
}

final class wire_cst_ir_span extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> text;

  @ffi.Bool()
  external bool bold;

  @ffi.Bool()
  external bool italic;

  @ffi.Bool()
  external bool strike;

  @ffi.Bool()
  external bool underline;

  @ffi.Bool()
  external bool code;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> href;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> diary_link_id;

  static ffi.Pointer<wire_cst_ir_span> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
    required bool bold,
    required bool italic,
    required bool strike,
    required bool underline,
    required bool code,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> href,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> diary_link_id,
  }) => $allocator<wire_cst_ir_span>()
    ..ref.text = text
    ..ref.bold = bold
    ..ref.italic = italic
    ..ref.strike = strike
    ..ref.underline = underline
    ..ref.code = code
    ..ref.href = href
    ..ref.diary_link_id = diary_link_id;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_String> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr,
    required int len,
  }) => $allocator<wire_cst_list_String>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_ir_block extends ffi.Struct {
  external ffi.Pointer<wire_cst_ir_block> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_ir_block> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_ir_block> ptr,
    required int len,
  }) => $allocator<wire_cst_list_ir_block>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_ir_cell extends ffi.Struct {
  external ffi.Pointer<wire_cst_ir_cell> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_ir_cell> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_ir_cell> ptr,
    required int len,
  }) => $allocator<wire_cst_list_ir_cell>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_ir_doc extends ffi.Struct {
  external ffi.Pointer<wire_cst_ir_doc> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_ir_doc> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_ir_doc> ptr,
    required int len,
  }) => $allocator<wire_cst_list_ir_doc>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_ir_list_item extends ffi.Struct {
  external ffi.Pointer<wire_cst_ir_list_item> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_ir_list_item> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_ir_list_item> ptr,
    required int len,
  }) => $allocator<wire_cst_list_ir_list_item>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_ir_row extends ffi.Struct {
  external ffi.Pointer<wire_cst_ir_row> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_ir_row> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_ir_row> ptr,
    required int len,
  }) => $allocator<wire_cst_list_ir_row>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_ir_span extends ffi.Struct {
  external ffi.Pointer<wire_cst_ir_span> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_ir_span> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_ir_span> ptr,
    required int len,
  }) => $allocator<wire_cst_list_ir_span>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_prim_u_8_strict> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Uint8> ptr,
    required int len,
  }) => $allocator<wire_cst_list_prim_u_8_strict>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_pdf_style extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> font_path;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> font_family;

  @ffi.Double()
  external double font_size_pt;

  @ffi.Double()
  external double line_spacing_em;

  @ffi.Bool()
  external bool first_line_indent;

  @ffi.Double()
  external double page_width_mm;

  @ffi.Double()
  external double page_height_mm;

  @ffi.Double()
  external double page_margin_mm;

  @ffi.Bool()
  external bool include_title;

  @ffi.Bool()
  external bool include_meta;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> video_label;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> audio_label;

  static ffi.Pointer<wire_cst_pdf_style> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> font_path,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> font_family,
    required double font_size_pt,
    required double line_spacing_em,
    required bool first_line_indent,
    required double page_width_mm,
    required double page_height_mm,
    required double page_margin_mm,
    required bool include_title,
    required bool include_meta,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> video_label,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> audio_label,
  }) => $allocator<wire_cst_pdf_style>()
    ..ref.font_path = font_path
    ..ref.font_family = font_family
    ..ref.font_size_pt = font_size_pt
    ..ref.line_spacing_em = line_spacing_em
    ..ref.first_line_indent = first_line_indent
    ..ref.page_width_mm = page_width_mm
    ..ref.page_height_mm = page_height_mm
    ..ref.page_margin_mm = page_margin_mm
    ..ref.include_title = include_title
    ..ref.include_meta = include_meta
    ..ref.video_label = video_label
    ..ref.audio_label = audio_label;
}
