name: moodiary_http
description: "HTTP 客户端与本地服务端口，实现走 Rust（reqwest / hyper）。"
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.13.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter

  moodiary_di: 0.0.1
  moodiary_logging: 0.0.1
  moodiary_rust: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  moodiary_lint: 0.0.1
