// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'constants.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `calculate_target_dimensions`, `compress`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ResizeOptions`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ImageCompress>>
abstract class ImageCompress implements RustOpaqueInterface {
  static Future<Uint8List> containWithOptions({
    required String filePath,
    CompressFormat? compressFormat,
    int? targetWidth,
    int? targetHeight,
    int? minWidth,
    int? minHeight,
    int? maxWidth,
    int? maxHeight,
    int? quality,
  }) => RustLib.instance.api.crateApiCompressImageCompressContainWithOptions(
    filePath: filePath,
    compressFormat: compressFormat,
    targetWidth: targetWidth,
    targetHeight: targetHeight,
    minWidth: minWidth,
    minHeight: minHeight,
    maxWidth: maxWidth,
    maxHeight: maxHeight,
    quality: quality,
  );
}
