// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Uint64List> buildPrefixTable({required List<String> pattern}) =>
    RustLib.instance.api.crateApiKmpBuildPrefixTable(pattern: pattern);

Future<Uint64List> kmpSearch({required String text, required String pattern}) =>
    RustLib.instance.api.crateApiKmpKmpSearch(text: text, pattern: pattern);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Kmp>>
abstract class Kmp implements RustOpaqueInterface {
  static Future<List<String>> findMatches(
          {required String text, required List<String> patterns}) =>
      RustLib.instance.api
          .crateApiKmpKmpFindMatches(text: text, patterns: patterns);

  static Future<String> replaceWithKmp(
          {required String text, required Map<String, String> replacements}) =>
      RustLib.instance.api
          .crateApiKmpKmpReplaceWithKmp(text: text, replacements: replacements);
}
