// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/assistant.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class FastLlmLib
    extends BaseEntrypoint<FastLlmLibApi, FastLlmLibApiImpl, FastLlmLibWire> {
  @internal
  static final instance = FastLlmLib._();

  FastLlmLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    FastLlmLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required FastLlmLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<FastLlmLibApiImpl, FastLlmLibWire>
  get apiImplConstructor => FastLlmLibApiImpl.new;

  @override
  WireConstructor<FastLlmLibWire> get wireConstructor =>
      FastLlmLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1843437611;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'fastllm',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class FastLlmLibApi extends BaseApi {
  Stream<RigStreamEvent> crateApiAssistantRigChatStream({
    required RigProviderConfig config,
    required String systemPrompt,
    required List<RigChatMessage> history,
    required List<RigToolDef> tools,
    required int maxTurns,
    required FutureOr<String> Function(String, String) toolDispatch,
  });
}

class FastLlmLibApiImpl extends FastLlmLibApiImplPlatform
    implements FastLlmLibApi {
  FastLlmLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<RigStreamEvent> crateApiAssistantRigChatStream({
    required RigProviderConfig config,
    required String systemPrompt,
    required List<RigChatMessage> history,
    required List<RigToolDef> tools,
    required int maxTurns,
    required FutureOr<String> Function(String, String) toolDispatch,
  }) {
    final sink = RustStreamSink<RigStreamEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            var arg0 = cst_encode_StreamSink_rig_stream_event_Dco(sink);
            var arg1 = cst_encode_box_autoadd_rig_provider_config(config);
            var arg2 = cst_encode_String(systemPrompt);
            var arg3 = cst_encode_list_rig_chat_message(history);
            var arg4 = cst_encode_list_rig_tool_def(tools);
            var arg5 = cst_encode_u_32(maxTurns);
            var arg6 =
                cst_encode_DartFn_Inputs_String_String_Output_String_AnyhowException(
                  toolDispatch,
                );
            return wire.wire__crate__api__assistant__rig_chat_stream(
              port_,
              arg0,
              arg1,
              arg2,
              arg3,
              arg4,
              arg5,
              arg6,
            );
          },
          codec: DcoCodec(
            decodeSuccessData: dco_decode_unit,
            decodeErrorData: dco_decode_AnyhowException,
          ),
          constMeta: kCrateApiAssistantRigChatStreamConstMeta,
          argValues: [
            sink,
            config,
            systemPrompt,
            history,
            tools,
            maxTurns,
            toolDispatch,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiAssistantRigChatStreamConstMeta =>
      const TaskConstMeta(
        debugName: "rig_chat_stream",
        argNames: [
          "sink",
          "config",
          "systemPrompt",
          "history",
          "tools",
          "maxTurns",
          "toolDispatch",
        ],
      );

  Future<void> Function(int, dynamic, dynamic)
  encode_DartFn_Inputs_String_String_Output_String_AnyhowException(
    FutureOr<String> Function(String, String) raw,
  ) {
    return (callId, rawArg0, rawArg1) async {
      final arg0 = dco_decode_String(rawArg0);
      final arg1 = dco_decode_String(rawArg1);

      Box<String>? rawOutput;
      Box<AnyhowException>? rawError;
      try {
        rawOutput = Box(await raw(arg0, arg1));
      } catch (e, s) {
        rawError = Box(AnyhowException("$e\n\n$s"));
      }

      final serializer = SseSerializer(generalizedFrbRustBinding);
      assert((rawOutput != null) ^ (rawError != null));
      if (rawOutput != null) {
        serializer.buffer.putUint8(0);
        sse_encode_String(rawOutput.value, serializer);
      } else {
        serializer.buffer.putUint8(1);
        sse_encode_AnyhowException(rawError!.value, serializer);
      }
      final output = serializer.intoRaw();

      generalizedFrbRustBinding.dartFnDeliverOutput(
        callId: callId,
        ptr: output.ptr,
        rustVecLen: output.rustVecLen,
        dataLen: output.dataLen,
      );
    };
  }

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  FutureOr<String> Function(String, String)
  dco_decode_DartFn_Inputs_String_String_Output_String_AnyhowException(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError('');
  }

  @protected
  Object dco_decode_DartOpaque(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return decodeDartOpaque(raw, generalizedFrbRustBinding);
  }

  @protected
  RustStreamSink<RigStreamEvent> dco_decode_StreamSink_rig_stream_event_Dco(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  RigProviderConfig dco_decode_box_autoadd_rig_provider_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rig_provider_config(raw);
  }

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RigChatMessage> dco_decode_list_rig_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rig_chat_message).toList();
  }

  @protected
  List<RigToolDef> dco_decode_list_rig_tool_def(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rig_tool_def).toList();
  }

  @protected
  RigChatMessage dco_decode_rig_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RigChatMessage(
      role: dco_decode_String(arr[0]),
      content: dco_decode_String(arr[1]),
      imageBase64: dco_decode_String(arr[2]),
      imageMime: dco_decode_String(arr[3]),
    );
  }

  @protected
  RigProviderConfig dco_decode_rig_provider_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return RigProviderConfig(
      protocol: dco_decode_String(arr[0]),
      apiKey: dco_decode_String(arr[1]),
      baseUrl: dco_decode_String(arr[2]),
      model: dco_decode_String(arr[3]),
      maxTokens: dco_decode_u_32(arr[4]),
      reasoningMode: dco_decode_String(arr[5]),
      reasoningEffort: dco_decode_String(arr[6]),
      reasoningBudget: dco_decode_u_32(arr[7]),
    );
  }

  @protected
  RigStreamEvent dco_decode_rig_stream_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return RigStreamEvent_TextDelta(dco_decode_String(raw[1]));
      case 1:
        return RigStreamEvent_ReasoningDelta(dco_decode_String(raw[1]));
      case 2:
        return RigStreamEvent_ToolCall(dco_decode_String(raw[1]));
      case 3:
        return RigStreamEvent_ToolStarted(
          callId: dco_decode_String(raw[1]),
          name: dco_decode_String(raw[2]),
          argsJson: dco_decode_String(raw[3]),
        );
      case 4:
        return RigStreamEvent_ToolFinished(
          callId: dco_decode_String(raw[1]),
          result: dco_decode_String(raw[2]),
        );
      case 5:
        return RigStreamEvent_Usage(
          inputTokens: dco_decode_u_32(raw[1]),
          outputTokens: dco_decode_u_32(raw[2]),
          cachedInputTokens: dco_decode_u_32(raw[3]),
          cacheWriteTokens: dco_decode_u_32(raw[4]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  RigToolDef dco_decode_rig_tool_def(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RigToolDef(
      name: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
      parametersJson: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_isize(deserializer);
    return decodeDartOpaque(inner, generalizedFrbRustBinding);
  }

  @protected
  RustStreamSink<RigStreamEvent> sse_decode_StreamSink_rig_stream_event_Dco(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  RigProviderConfig sse_decode_box_autoadd_rig_provider_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rig_provider_config(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RigChatMessage> sse_decode_list_rig_chat_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RigChatMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rig_chat_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<RigToolDef> sse_decode_list_rig_tool_def(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RigToolDef>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rig_tool_def(deserializer));
    }
    return ans_;
  }

  @protected
  RigChatMessage sse_decode_rig_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_role = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_imageBase64 = sse_decode_String(deserializer);
    var var_imageMime = sse_decode_String(deserializer);
    return RigChatMessage(
      role: var_role,
      content: var_content,
      imageBase64: var_imageBase64,
      imageMime: var_imageMime,
    );
  }

  @protected
  RigProviderConfig sse_decode_rig_provider_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_protocol = sse_decode_String(deserializer);
    var var_apiKey = sse_decode_String(deserializer);
    var var_baseUrl = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_maxTokens = sse_decode_u_32(deserializer);
    var var_reasoningMode = sse_decode_String(deserializer);
    var var_reasoningEffort = sse_decode_String(deserializer);
    var var_reasoningBudget = sse_decode_u_32(deserializer);
    return RigProviderConfig(
      protocol: var_protocol,
      apiKey: var_apiKey,
      baseUrl: var_baseUrl,
      model: var_model,
      maxTokens: var_maxTokens,
      reasoningMode: var_reasoningMode,
      reasoningEffort: var_reasoningEffort,
      reasoningBudget: var_reasoningBudget,
    );
  }

  @protected
  RigStreamEvent sse_decode_rig_stream_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return RigStreamEvent_TextDelta(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return RigStreamEvent_ReasoningDelta(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return RigStreamEvent_ToolCall(var_field0);
      case 3:
        var var_callId = sse_decode_String(deserializer);
        var var_name = sse_decode_String(deserializer);
        var var_argsJson = sse_decode_String(deserializer);
        return RigStreamEvent_ToolStarted(
          callId: var_callId,
          name: var_name,
          argsJson: var_argsJson,
        );
      case 4:
        var var_callId = sse_decode_String(deserializer);
        var var_result = sse_decode_String(deserializer);
        return RigStreamEvent_ToolFinished(
          callId: var_callId,
          result: var_result,
        );
      case 5:
        var var_inputTokens = sse_decode_u_32(deserializer);
        var var_outputTokens = sse_decode_u_32(deserializer);
        var var_cachedInputTokens = sse_decode_u_32(deserializer);
        var var_cacheWriteTokens = sse_decode_u_32(deserializer);
        return RigStreamEvent_Usage(
          inputTokens: var_inputTokens,
          outputTokens: var_outputTokens,
          cachedInputTokens: var_cachedInputTokens,
          cacheWriteTokens: var_cacheWriteTokens,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  RigToolDef sse_decode_rig_tool_def(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_parametersJson = sse_decode_String(deserializer);
    return RigToolDef(
      name: var_name,
      description: var_description,
      parametersJson: var_parametersJson,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformPointer
  cst_encode_DartFn_Inputs_String_String_Output_String_AnyhowException(
    FutureOr<String> Function(String, String) raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_DartOpaque(
      encode_DartFn_Inputs_String_String_Output_String_AnyhowException(raw),
    );
  }

  @protected
  PlatformPointer cst_encode_DartOpaque(Object raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return encodeDartOpaque(
      raw,
      portManager.dartHandlerPort,
      generalizedFrbRustBinding,
    );
  }

  @protected
  int cst_encode_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_DartFn_Inputs_String_String_Output_String_AnyhowException(
    FutureOr<String> Function(String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_DartOpaque(
      encode_DartFn_Inputs_String_String_Output_String_AnyhowException(self),
      serializer,
    );
  }

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_isize(
      PlatformPointerUtil.ptrToPlatformInt64(
        encodeDartOpaque(
          self,
          portManager.dartHandlerPort,
          generalizedFrbRustBinding,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_rig_stream_event_Dco(
    RustStreamSink<RigStreamEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_rig_stream_event,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_rig_provider_config(
    RigProviderConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rig_provider_config(self, serializer);
  }

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_rig_chat_message(
    List<RigChatMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rig_chat_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rig_tool_def(
    List<RigToolDef> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rig_tool_def(item, serializer);
    }
  }

  @protected
  void sse_encode_rig_chat_message(
    RigChatMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.imageBase64, serializer);
    sse_encode_String(self.imageMime, serializer);
  }

  @protected
  void sse_encode_rig_provider_config(
    RigProviderConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.protocol, serializer);
    sse_encode_String(self.apiKey, serializer);
    sse_encode_String(self.baseUrl, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_u_32(self.maxTokens, serializer);
    sse_encode_String(self.reasoningMode, serializer);
    sse_encode_String(self.reasoningEffort, serializer);
    sse_encode_u_32(self.reasoningBudget, serializer);
  }

  @protected
  void sse_encode_rig_stream_event(
    RigStreamEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case RigStreamEvent_TextDelta(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case RigStreamEvent_ReasoningDelta(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case RigStreamEvent_ToolCall(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case RigStreamEvent_ToolStarted(
        callId: final callId,
        name: final name,
        argsJson: final argsJson,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(callId, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(argsJson, serializer);
      case RigStreamEvent_ToolFinished(
        callId: final callId,
        result: final result,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_String(callId, serializer);
        sse_encode_String(result, serializer);
      case RigStreamEvent_Usage(
        inputTokens: final inputTokens,
        outputTokens: final outputTokens,
        cachedInputTokens: final cachedInputTokens,
        cacheWriteTokens: final cacheWriteTokens,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_u_32(inputTokens, serializer);
        sse_encode_u_32(outputTokens, serializer);
        sse_encode_u_32(cachedInputTokens, serializer);
        sse_encode_u_32(cacheWriteTokens, serializer);
    }
  }

  @protected
  void sse_encode_rig_tool_def(RigToolDef self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.parametersJson, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
