targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            moodiary: lib/src/db/database.dart
          schema_dir: drift_schemas/
          test_dir: test/drift/
          sql:
            dialect: sqlite
            options:
              version: "3.49"
              modules: [fts5]
