// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = DcoCodec,
    default_rust_opaque = RustOpaqueNom,
    default_rust_auto_opaque = RustAutoOpaqueNom,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1843437611;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__assistant__rig_chat_stream_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    sink: impl CstDecode<
        StreamSink<
            crate::api::assistant::RigStreamEvent,
            flutter_rust_bridge::for_generated::DcoCodec,
        >,
    >,
    config: impl CstDecode<crate::api::assistant::RigProviderConfig>,
    system_prompt: impl CstDecode<String>,
    history: impl CstDecode<Vec<crate::api::assistant::RigChatMessage>>,
    tools: impl CstDecode<Vec<crate::api::assistant::RigToolDef>>,
    max_turns: impl CstDecode<u32>,
    tool_dispatch: impl CstDecode<flutter_rust_bridge::DartOpaque>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "rig_chat_stream",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_sink = sink.cst_decode();
            let api_config = config.cst_decode();
            let api_system_prompt = system_prompt.cst_decode();
            let api_history = history.cst_decode();
            let api_tools = tools.cst_decode();
            let api_max_turns = max_turns.cst_decode();
            let api_tool_dispatch =
                decode_DartFn_Inputs_String_String_Output_String_AnyhowException(
                    tool_dispatch.cst_decode(),
                );
            move |context| async move {
                transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::assistant::rig_chat_stream(
                            api_sink,
                            api_config,
                            api_system_prompt,
                            api_history,
                            api_tools,
                            api_max_turns,
                            api_tool_dispatch,
                        )
                        .await?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: static_checks

#[allow(clippy::unnecessary_literal_unwrap)]
const _: fn() = || {
    {
        let RigChatMessage = None::<crate::api::assistant::RigChatMessage>.unwrap();
        let _: String = RigChatMessage.role;
        let _: String = RigChatMessage.content;
        let _: String = RigChatMessage.image_base64;
        let _: String = RigChatMessage.image_mime;
    }
    {
        let RigProviderConfig = None::<crate::api::assistant::RigProviderConfig>.unwrap();
        let _: String = RigProviderConfig.protocol;
        let _: String = RigProviderConfig.api_key;
        let _: String = RigProviderConfig.base_url;
        let _: String = RigProviderConfig.model;
        let _: u32 = RigProviderConfig.max_tokens;
        let _: String = RigProviderConfig.reasoning_mode;
        let _: String = RigProviderConfig.reasoning_effort;
        let _: u32 = RigProviderConfig.reasoning_budget;
    }
    match None::<crate::api::assistant::RigStreamEvent>.unwrap() {
        crate::api::assistant::RigStreamEvent::TextDelta(field0) => {
            let _: String = field0;
        }
        crate::api::assistant::RigStreamEvent::ReasoningDelta(field0) => {
            let _: String = field0;
        }
        crate::api::assistant::RigStreamEvent::ToolCall(field0) => {
            let _: String = field0;
        }
        crate::api::assistant::RigStreamEvent::ToolStarted {
            call_id,
            name,
            args_json,
        } => {
            let _: String = call_id;
            let _: String = name;
            let _: String = args_json;
        }
        crate::api::assistant::RigStreamEvent::ToolFinished { call_id, result } => {
            let _: String = call_id;
            let _: String = result;
        }
        crate::api::assistant::RigStreamEvent::Usage {
            input_tokens,
            output_tokens,
            cached_input_tokens,
            cache_write_tokens,
        } => {
            let _: u32 = input_tokens;
            let _: u32 = output_tokens;
            let _: u32 = cached_input_tokens;
            let _: u32 = cache_write_tokens;
        }
    }
    {
        let RigToolDef = None::<crate::api::assistant::RigToolDef>.unwrap();
        let _: String = RigToolDef.name;
        let _: String = RigToolDef.description;
        let _: String = RigToolDef.parameters_json;
    }
};

// Section: related_funcs

fn decode_DartFn_Inputs_String_String_Output_String_AnyhowException(
    dart_opaque: flutter_rust_bridge::DartOpaque,
) -> impl Fn(
    String,
    String,
) -> flutter_rust_bridge::DartFnFuture<
    std::result::Result<String, flutter_rust_bridge::for_generated::anyhow::Error>,
> {
    use flutter_rust_bridge::IntoDart;

    async fn body(
        dart_opaque: flutter_rust_bridge::DartOpaque,
        arg0: String,
        arg1: String,
    ) -> std::result::Result<String, flutter_rust_bridge::for_generated::anyhow::Error> {
        let args = vec![
            arg0.into_into_dart().into_dart(),
            arg1.into_into_dart().into_dart(),
        ];
        let message = FLUTTER_RUST_BRIDGE_HANDLER
            .dart_fn_invoke(dart_opaque, args)
            .await;

        let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
        let action = deserializer.cursor.read_u8().unwrap();
        let ans = match action {
            0 => std::result::Result::Ok(<String>::sse_decode(&mut deserializer)),
            1 => std::result::Result::Err(
                <flutter_rust_bridge::for_generated::anyhow::Error>::sse_decode(&mut deserializer),
            ),
            _ => unreachable!(),
        };
        deserializer.end();
        ans
    }

    move |arg0: String, arg1: String| {
        flutter_rust_bridge::for_generated::convert_into_dart_fn_future(body(
            dart_opaque.clone(),
            arg0,
            arg1,
        ))
    }
}

// Section: dart2rust

impl CstDecode<isize> for isize {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> isize {
        self
    }
}
impl CstDecode<u32> for u32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u32 {
        self
    }
}
impl CstDecode<u8> for u8 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u8 {
        self
    }
}
impl CstDecode<usize> for usize {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> usize {
        self
    }
}
impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for flutter_rust_bridge::DartOpaque {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return unsafe { flutter_rust_bridge::for_generated::sse_decode_dart_opaque(inner) };
    }
}

impl SseDecode
    for StreamSink<
        crate::api::assistant::RigStreamEvent,
        flutter_rust_bridge::for_generated::DcoCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for isize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::assistant::RigChatMessage> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::assistant::RigChatMessage>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::assistant::RigToolDef> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::assistant::RigToolDef>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::assistant::RigChatMessage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_role = <String>::sse_decode(deserializer);
        let mut var_content = <String>::sse_decode(deserializer);
        let mut var_imageBase64 = <String>::sse_decode(deserializer);
        let mut var_imageMime = <String>::sse_decode(deserializer);
        return crate::api::assistant::RigChatMessage {
            role: var_role,
            content: var_content,
            image_base64: var_imageBase64,
            image_mime: var_imageMime,
        };
    }
}

impl SseDecode for crate::api::assistant::RigProviderConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_protocol = <String>::sse_decode(deserializer);
        let mut var_apiKey = <String>::sse_decode(deserializer);
        let mut var_baseUrl = <String>::sse_decode(deserializer);
        let mut var_model = <String>::sse_decode(deserializer);
        let mut var_maxTokens = <u32>::sse_decode(deserializer);
        let mut var_reasoningMode = <String>::sse_decode(deserializer);
        let mut var_reasoningEffort = <String>::sse_decode(deserializer);
        let mut var_reasoningBudget = <u32>::sse_decode(deserializer);
        return crate::api::assistant::RigProviderConfig {
            protocol: var_protocol,
            api_key: var_apiKey,
            base_url: var_baseUrl,
            model: var_model,
            max_tokens: var_maxTokens,
            reasoning_mode: var_reasoningMode,
            reasoning_effort: var_reasoningEffort,
            reasoning_budget: var_reasoningBudget,
        };
    }
}

impl SseDecode for crate::api::assistant::RigStreamEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::assistant::RigStreamEvent::TextDelta(var_field0);
            }
            1 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::assistant::RigStreamEvent::ReasoningDelta(var_field0);
            }
            2 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::assistant::RigStreamEvent::ToolCall(var_field0);
            }
            3 => {
                let mut var_callId = <String>::sse_decode(deserializer);
                let mut var_name = <String>::sse_decode(deserializer);
                let mut var_argsJson = <String>::sse_decode(deserializer);
                return crate::api::assistant::RigStreamEvent::ToolStarted {
                    call_id: var_callId,
                    name: var_name,
                    args_json: var_argsJson,
                };
            }
            4 => {
                let mut var_callId = <String>::sse_decode(deserializer);
                let mut var_result = <String>::sse_decode(deserializer);
                return crate::api::assistant::RigStreamEvent::ToolFinished {
                    call_id: var_callId,
                    result: var_result,
                };
            }
            5 => {
                let mut var_inputTokens = <u32>::sse_decode(deserializer);
                let mut var_outputTokens = <u32>::sse_decode(deserializer);
                let mut var_cachedInputTokens = <u32>::sse_decode(deserializer);
                let mut var_cacheWriteTokens = <u32>::sse_decode(deserializer);
                return crate::api::assistant::RigStreamEvent::Usage {
                    input_tokens: var_inputTokens,
                    output_tokens: var_outputTokens,
                    cached_input_tokens: var_cachedInputTokens,
                    cache_write_tokens: var_cacheWriteTokens,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::assistant::RigToolDef {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_description = <String>::sse_decode(deserializer);
        let mut var_parametersJson = <String>::sse_decode(deserializer);
        return crate::api::assistant::RigToolDef {
            name: var_name,
            description: var_description,
            parameters_json: var_parametersJson,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::assistant::RigChatMessage> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.role.into_into_dart().into_dart(),
            self.0.content.into_into_dart().into_dart(),
            self.0.image_base64.into_into_dart().into_dart(),
            self.0.image_mime.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::assistant::RigChatMessage>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::assistant::RigChatMessage>>
    for crate::api::assistant::RigChatMessage
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::assistant::RigChatMessage> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::assistant::RigProviderConfig> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.protocol.into_into_dart().into_dart(),
            self.0.api_key.into_into_dart().into_dart(),
            self.0.base_url.into_into_dart().into_dart(),
            self.0.model.into_into_dart().into_dart(),
            self.0.max_tokens.into_into_dart().into_dart(),
            self.0.reasoning_mode.into_into_dart().into_dart(),
            self.0.reasoning_effort.into_into_dart().into_dart(),
            self.0.reasoning_budget.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::assistant::RigProviderConfig>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::assistant::RigProviderConfig>>
    for crate::api::assistant::RigProviderConfig
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::assistant::RigProviderConfig> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::assistant::RigStreamEvent> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self.0 {
            crate::api::assistant::RigStreamEvent::TextDelta(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::assistant::RigStreamEvent::ReasoningDelta(field0) => {
                [1.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::assistant::RigStreamEvent::ToolCall(field0) => {
                [2.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::assistant::RigStreamEvent::ToolStarted {
                call_id,
                name,
                args_json,
            } => [
                3.into_dart(),
                call_id.into_into_dart().into_dart(),
                name.into_into_dart().into_dart(),
                args_json.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::assistant::RigStreamEvent::ToolFinished { call_id, result } => [
                4.into_dart(),
                call_id.into_into_dart().into_dart(),
                result.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::assistant::RigStreamEvent::Usage {
                input_tokens,
                output_tokens,
                cached_input_tokens,
                cache_write_tokens,
            } => [
                5.into_dart(),
                input_tokens.into_into_dart().into_dart(),
                output_tokens.into_into_dart().into_dart(),
                cached_input_tokens.into_into_dart().into_dart(),
                cache_write_tokens.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::assistant::RigStreamEvent>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::assistant::RigStreamEvent>>
    for crate::api::assistant::RigStreamEvent
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::assistant::RigStreamEvent> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::assistant::RigToolDef> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.name.into_into_dart().into_dart(),
            self.0.description.into_into_dart().into_dart(),
            self.0.parameters_json.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::assistant::RigToolDef>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::assistant::RigToolDef>>
    for crate::api::assistant::RigToolDef
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::assistant::RigToolDef> {
        self.into()
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for flutter_rust_bridge::DartOpaque {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <usize>::sse_encode(self.encode(), serializer);
    }
}

impl SseEncode
    for StreamSink<
        crate::api::assistant::RigStreamEvent,
        flutter_rust_bridge::for_generated::DcoCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for isize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_i64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::assistant::RigChatMessage> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::assistant::RigChatMessage>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::assistant::RigToolDef> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::assistant::RigToolDef>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::assistant::RigChatMessage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.role, serializer);
        <String>::sse_encode(self.content, serializer);
        <String>::sse_encode(self.image_base64, serializer);
        <String>::sse_encode(self.image_mime, serializer);
    }
}

impl SseEncode for crate::api::assistant::RigProviderConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.protocol, serializer);
        <String>::sse_encode(self.api_key, serializer);
        <String>::sse_encode(self.base_url, serializer);
        <String>::sse_encode(self.model, serializer);
        <u32>::sse_encode(self.max_tokens, serializer);
        <String>::sse_encode(self.reasoning_mode, serializer);
        <String>::sse_encode(self.reasoning_effort, serializer);
        <u32>::sse_encode(self.reasoning_budget, serializer);
    }
}

impl SseEncode for crate::api::assistant::RigStreamEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::assistant::RigStreamEvent::TextDelta(field0) => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::api::assistant::RigStreamEvent::ReasoningDelta(field0) => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::api::assistant::RigStreamEvent::ToolCall(field0) => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::api::assistant::RigStreamEvent::ToolStarted {
                call_id,
                name,
                args_json,
            } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(call_id, serializer);
                <String>::sse_encode(name, serializer);
                <String>::sse_encode(args_json, serializer);
            }
            crate::api::assistant::RigStreamEvent::ToolFinished { call_id, result } => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(call_id, serializer);
                <String>::sse_encode(result, serializer);
            }
            crate::api::assistant::RigStreamEvent::Usage {
                input_tokens,
                output_tokens,
                cached_input_tokens,
                cache_write_tokens,
            } => {
                <i32>::sse_encode(5, serializer);
                <u32>::sse_encode(input_tokens, serializer);
                <u32>::sse_encode(output_tokens, serializer);
                <u32>::sse_encode(cached_input_tokens, serializer);
                <u32>::sse_encode(cache_write_tokens, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::assistant::RigToolDef {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.description, serializer);
        <String>::sse_encode(self.parameters_json, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    // Section: dart2rust

    impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error>
        for *mut wire_cst_list_prim_u_8_strict
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
            unimplemented!()
        }
    }
    impl CstDecode<flutter_rust_bridge::DartOpaque> for *const std::ffi::c_void {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::DartOpaque {
            unsafe { flutter_rust_bridge::for_generated::cst_decode_dart_opaque(self as _) }
        }
    }
    impl
        CstDecode<
            StreamSink<
                crate::api::assistant::RigStreamEvent,
                flutter_rust_bridge::for_generated::DcoCodec,
            >,
        > for *mut wire_cst_list_prim_u_8_strict
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(
            self,
        ) -> StreamSink<
            crate::api::assistant::RigStreamEvent,
            flutter_rust_bridge::for_generated::DcoCodec,
        > {
            let raw: String = self.cst_decode();
            StreamSink::deserialize(raw)
        }
    }
    impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            let vec: Vec<u8> = self.cst_decode();
            String::from_utf8(vec).unwrap()
        }
    }
    impl CstDecode<crate::api::assistant::RigProviderConfig> for *mut wire_cst_rig_provider_config {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::assistant::RigProviderConfig {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::assistant::RigProviderConfig>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl CstDecode<Vec<crate::api::assistant::RigChatMessage>> for *mut wire_cst_list_rig_chat_message {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::assistant::RigChatMessage> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<crate::api::assistant::RigToolDef>> for *mut wire_cst_list_rig_tool_def {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::assistant::RigToolDef> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<crate::api::assistant::RigChatMessage> for wire_cst_rig_chat_message {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::assistant::RigChatMessage {
            crate::api::assistant::RigChatMessage {
                role: self.role.cst_decode(),
                content: self.content.cst_decode(),
                image_base64: self.image_base64.cst_decode(),
                image_mime: self.image_mime.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::assistant::RigProviderConfig> for wire_cst_rig_provider_config {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::assistant::RigProviderConfig {
            crate::api::assistant::RigProviderConfig {
                protocol: self.protocol.cst_decode(),
                api_key: self.api_key.cst_decode(),
                base_url: self.base_url.cst_decode(),
                model: self.model.cst_decode(),
                max_tokens: self.max_tokens.cst_decode(),
                reasoning_mode: self.reasoning_mode.cst_decode(),
                reasoning_effort: self.reasoning_effort.cst_decode(),
                reasoning_budget: self.reasoning_budget.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::assistant::RigStreamEvent> for wire_cst_rig_stream_event {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::assistant::RigStreamEvent {
            match self.tag {
                0 => {
                    let ans = unsafe { self.kind.TextDelta };
                    crate::api::assistant::RigStreamEvent::TextDelta(ans.field0.cst_decode())
                }
                1 => {
                    let ans = unsafe { self.kind.ReasoningDelta };
                    crate::api::assistant::RigStreamEvent::ReasoningDelta(ans.field0.cst_decode())
                }
                2 => {
                    let ans = unsafe { self.kind.ToolCall };
                    crate::api::assistant::RigStreamEvent::ToolCall(ans.field0.cst_decode())
                }
                3 => {
                    let ans = unsafe { self.kind.ToolStarted };
                    crate::api::assistant::RigStreamEvent::ToolStarted {
                        call_id: ans.call_id.cst_decode(),
                        name: ans.name.cst_decode(),
                        args_json: ans.args_json.cst_decode(),
                    }
                }
                4 => {
                    let ans = unsafe { self.kind.ToolFinished };
                    crate::api::assistant::RigStreamEvent::ToolFinished {
                        call_id: ans.call_id.cst_decode(),
                        result: ans.result.cst_decode(),
                    }
                }
                5 => {
                    let ans = unsafe { self.kind.Usage };
                    crate::api::assistant::RigStreamEvent::Usage {
                        input_tokens: ans.input_tokens.cst_decode(),
                        output_tokens: ans.output_tokens.cst_decode(),
                        cached_input_tokens: ans.cached_input_tokens.cst_decode(),
                        cache_write_tokens: ans.cache_write_tokens.cst_decode(),
                    }
                }
                _ => unreachable!(),
            }
        }
    }
    impl CstDecode<crate::api::assistant::RigToolDef> for wire_cst_rig_tool_def {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::assistant::RigToolDef {
            crate::api::assistant::RigToolDef {
                name: self.name.cst_decode(),
                description: self.description.cst_decode(),
                parameters_json: self.parameters_json.cst_decode(),
            }
        }
    }
    impl NewWithNullPtr for wire_cst_rig_chat_message {
        fn new_with_null_ptr() -> Self {
            Self {
                role: core::ptr::null_mut(),
                content: core::ptr::null_mut(),
                image_base64: core::ptr::null_mut(),
                image_mime: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_rig_chat_message {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_rig_provider_config {
        fn new_with_null_ptr() -> Self {
            Self {
                protocol: core::ptr::null_mut(),
                api_key: core::ptr::null_mut(),
                base_url: core::ptr::null_mut(),
                model: core::ptr::null_mut(),
                max_tokens: Default::default(),
                reasoning_mode: core::ptr::null_mut(),
                reasoning_effort: core::ptr::null_mut(),
                reasoning_budget: Default::default(),
            }
        }
    }
    impl Default for wire_cst_rig_provider_config {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_rig_stream_event {
        fn new_with_null_ptr() -> Self {
            Self {
                tag: -1,
                kind: RigStreamEventKind { nil__: () },
            }
        }
    }
    impl Default for wire_cst_rig_stream_event {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_rig_tool_def {
        fn new_with_null_ptr() -> Self {
            Self {
                name: core::ptr::null_mut(),
                description: core::ptr::null_mut(),
                parameters_json: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_rig_tool_def {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_llm_wire__crate__api__assistant__rig_chat_stream(
        port_: i64,
        sink: *mut wire_cst_list_prim_u_8_strict,
        config: *mut wire_cst_rig_provider_config,
        system_prompt: *mut wire_cst_list_prim_u_8_strict,
        history: *mut wire_cst_list_rig_chat_message,
        tools: *mut wire_cst_list_rig_tool_def,
        max_turns: u32,
        tool_dispatch: *const std::ffi::c_void,
    ) {
        wire__crate__api__assistant__rig_chat_stream_impl(
            port_,
            sink,
            config,
            system_prompt,
            history,
            tools,
            max_turns,
            tool_dispatch,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_llm_cst_new_box_autoadd_rig_provider_config()
    -> *mut wire_cst_rig_provider_config {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_rig_provider_config::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_llm_cst_new_list_prim_u_8_strict(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_strict {
        let ans = wire_cst_list_prim_u_8_strict {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_llm_cst_new_list_rig_chat_message(
        len: i32,
    ) -> *mut wire_cst_list_rig_chat_message {
        let wrap = wire_cst_list_rig_chat_message {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_rig_chat_message>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_fast_llm_cst_new_list_rig_tool_def(
        len: i32,
    ) -> *mut wire_cst_list_rig_tool_def {
        let wrap = wire_cst_list_rig_tool_def {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_rig_tool_def>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_strict {
        ptr: *mut u8,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_rig_chat_message {
        ptr: *mut wire_cst_rig_chat_message,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_rig_tool_def {
        ptr: *mut wire_cst_rig_tool_def,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_rig_chat_message {
        role: *mut wire_cst_list_prim_u_8_strict,
        content: *mut wire_cst_list_prim_u_8_strict,
        image_base64: *mut wire_cst_list_prim_u_8_strict,
        image_mime: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_rig_provider_config {
        protocol: *mut wire_cst_list_prim_u_8_strict,
        api_key: *mut wire_cst_list_prim_u_8_strict,
        base_url: *mut wire_cst_list_prim_u_8_strict,
        model: *mut wire_cst_list_prim_u_8_strict,
        max_tokens: u32,
        reasoning_mode: *mut wire_cst_list_prim_u_8_strict,
        reasoning_effort: *mut wire_cst_list_prim_u_8_strict,
        reasoning_budget: u32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_rig_stream_event {
        tag: i32,
        kind: RigStreamEventKind,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub union RigStreamEventKind {
        TextDelta: wire_cst_RigStreamEvent_TextDelta,
        ReasoningDelta: wire_cst_RigStreamEvent_ReasoningDelta,
        ToolCall: wire_cst_RigStreamEvent_ToolCall,
        ToolStarted: wire_cst_RigStreamEvent_ToolStarted,
        ToolFinished: wire_cst_RigStreamEvent_ToolFinished,
        Usage: wire_cst_RigStreamEvent_Usage,
        nil__: (),
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_RigStreamEvent_TextDelta {
        field0: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_RigStreamEvent_ReasoningDelta {
        field0: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_RigStreamEvent_ToolCall {
        field0: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_RigStreamEvent_ToolStarted {
        call_id: *mut wire_cst_list_prim_u_8_strict,
        name: *mut wire_cst_list_prim_u_8_strict,
        args_json: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_RigStreamEvent_ToolFinished {
        call_id: *mut wire_cst_list_prim_u_8_strict,
        result: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_RigStreamEvent_Usage {
        input_tokens: u32,
        output_tokens: u32,
        cached_input_tokens: u32,
        cache_write_tokens: u32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_rig_tool_def {
        name: *mut wire_cst_list_prim_u_8_strict,
        description: *mut wire_cst_list_prim_u_8_strict,
        parameters_json: *mut wire_cst_list_prim_u_8_strict,
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
