name: Git Cliff (develop)

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog using Git Cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit and push changelog changes
        run: |
          git checkout -b changelog-update-develop
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "chore: update changelog on develop"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git changelog-update-develop

      - name: Create Pull Request
        run: |
          gh pr create --base develop --head changelog-update-develop --title "chore: update changelog" --body "This PR updates the changelog after recent changes on develop." --label bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Merge Pull Request
        run: |
          gh pr merge --merge --delete-branch changelog-update-develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}