name: Label PR Based on Conventional Commits

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]

permissions:
  pull-requests: write

jobs:
  label-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Add Label to PR
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          case "$PR_TITLE" in
            feat*) label=feat ;;
            fix*) label=fix ;;
            chore*) label=chore ;;
            docs*) label=docs ;;
            style*) label=style ;;
            refactor*) label=refactor ;;
            perf*) label=perf ;;
            test*) label=test ;;
            build*) label=build ;;
            ci*) label=ci ;;
            revert*) label=revert ;;
            *) label='?' ;;
          esac
          gh api --method POST "repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/labels" -f "labels[]=$label" --silent
